### ISSUE TITLE
 error trying to pass augmentation arguments to transform - transforms_interface.py", line 112, in apply_with_params

### ISSUE THREAD

**Issue by RachelRamirez** [albumentations-team/albumentations#1116]
## 🐛 Bug

My neural network is no longer taking my images (a dataset merged with unaugmented and augmented images) and training.  It seems to quit after getting to my transform function which sends specific augmentations for each run through to the images.  This function used to work but no longer does as of this evening.  
  
## To Reproduce

1.  Run google colab notebook to augment images according to settings per specified run in dataframe
2.  train CNN with these new images
3.  error when transform function reads arguments passed from dataframe

Error Message:

> File "/usr/local/lib/python3.7/dist-packages/albumentations/core/transforms_interface.py", line 112, in apply_with_params
>     res[key] = target_function(arg, **dict(params, **target_dependencies))
> 
>   File "/usr/local/lib/python3.7/dist-packages/albumentations/augmentations/crops/transforms.py", line 89, in apply
>     return F.center_crop(img, self.height, self.width)
> 
>   File "/usr/local/lib/python3.7/dist-packages/albumentations/augmentations/crops/functional.py", line 125, in center_crop
>     img = img[y1:y2, x1:x2]
> 
> TypeError: slice indices must be integers or None or have an __index__ method
> 
> 
> 	 [[{{node PyFunc}}]]
> 	 [[IteratorGetNext]]
> 	 [[IteratorGetNext/_4]]
>   (1) INVALID_ARGUMENT:  TypeError: slice indices must be integers or None or have an __index__ method
> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/script_ops.py", line 275, in __call__
>     ret = func(*args)
> 
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py", line 649, in wrapper
>     return func(*args, **kwargs)
> 
>   File "<ipython-input-169-a4b78fff2a00>", line 8, in aug_fn
>     aug_data = transforms(**data)
> 
>   File "/usr/local/lib/python3.7/dist-packages/albumentations/core/composition.py", line 210, in __call__
>     data = t(force_apply=force_apply, **data)
> 
>   File "/usr/local/lib/python3.7/dist-packages/albumentations/core/transforms_interface.py", line 97, in __call__
>     return self.apply_with_params(params, **kwargs)
> 
>   File "/usr/local/lib/python3.7/dist-packages/albumentations/core/transforms_interface.py", line 112, in apply_with_params
>     res[key] = target_function(arg, **dict(params, **target_dependencies))
> 
>   File "/usr/local/lib/python3.7/dist-packages/albumentations/augmentations/crops/transforms.py", line 89, in apply
>     return F.center_crop(img, self.height, self.width)
> 
>   File "/usr/local/lib/python3.7/dist-packages/albumentations/augmentations/crops/functional.py", line 125, in center_crop
>     img = img[y1:y2, x1:x2]
> 
> TypeError: slice indices must be integers or None or have an __index__ method
> 
> 
> 	 [[{{node PyFunc}}]]
> 	 [[IteratorGetNext]]
> 0 successful operations.
> 0 derived errors ignored. [Op:__inference_train_function_104687]
> 
> Function call stack:
> train_function -> train_function

## Expected behavior

For months it's worked fine, my neural network trains on the augmented images.  Now it cannot create the augmentations. 

## Environment

 - Albumentations version (e.g., 0.1.8):  1.1.0
 - Python version (e.g., 3.7):  3.7
 - OS (e.g., Linux):  Windows 10  using Google Colab
 - How you installed albumentations (`conda`, `pip`, source):  yes pip
 - Any other relevant information:  my code was working fine for months, then open-cv updated 2 weeks ago and caused a problem with albumentations.  once that was resolved my code worked again, but now this has happened.  I think it may be because I refer to my transforms inside of a for-loop as a global so that I can access them.    My code for this problem starts around line [link to my code](https://colab.research.google.com/drive/1redPQrDTSkK00UV6TxWK8KNG3gCMTnN9?usp=sharing)

## Additional context

I previously posted a question about open-cv-headless which you all resolved, thank you.  Everything worked for another 1-2 weeks but this error is now popping up.

**Comment by RachelRamirez** [comment]
I closed this issue because I resolved it.  A decimal had snuck into one of my crop values.  It was hard to find because it was not the immediate augmentation I was working on, it was a planned run later.
