### ISSUE TITLE
TypeError: __call__() got an unexpected keyword argument 'force_apply'

### ISSUE THREAD

**Issue by Gh0stW0If** [albumentations-team/albumentations#1190]
Traceback (most recent call last):
  File "segment.py", line 210, in <module>
    for batch_idx, (img, lab) in enumerate(trainloader):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "segment.py", line 96, in __getitem__
    augmented = self.transform(image=img,mask = lab)
  File "/root/miniconda3/lib/python3.8/site-packages/albumentations/core/composition.py", line 182, in __call__
    data = t(force_apply=force_apply, **data)
TypeError: __call__() got an unexpected keyword argument 'force_apply'

I donnot know why it says 'unexpected keyward argument'force_apply'',what's the problem

**Comment by Mac-jie** [comment]
Did you solved it?

**Comment by i-aki-y** [comment]
In my case, when I wrongly set a non-Transform object in the `A.Compose`, I got a similar TypeError.

An example:
```py
## `HorizontalFlip` is missing `()`
transforms = A.Compose([A.HorizontalFlip])  # 
transforms(image=image)
#->  TypeError: __init__() got an unexpected keyword argument 'force_apply'

# fixed version
transforms = A.Compose([A.HorizontalFlip()])
transforms(image=image) # OK

```

**Comment by SunHaozhe** [comment]
The problem is probably that, inside `A.Compose`, you used a transform function which does not come from `albumentations`, this external transform function does not have the keyword argument "force_apply". 

To solve this problem, you can apply this external transform function outside `A.Compose`
