### ISSUE TITLE
ToRGB cannot be deserialized

### ISSUE THREAD

**Issue by domef** [albumentations-team/albumentations#1383]
## 🐛 Bug

The transform `albumentations.augmentations.transforms.ToRGB` cannot be deserialized with the `A.from_dict` method, a `KeyError` is thrown.

## To Reproduce

Here I show an example to reproduce the bug:

```python
import albumentations as A

d = {
    "__version__": "1.3.0",
    "transform": {
        "__class_fullname__": "Compose",
        "additional_targets": {},
        "p": 1.0,
        "transforms": [
            {
                "__class_fullname__": "albumentations.augmentations.transforms.ToRGB",
                "p": 1.0,
            }
        ],
    },
}
A.from_dict(d)

```
This is the stack trace:
```
Traceback (most recent call last):
  File "/home/federico/file.py", line 12, in <module>
    A.from_dict(d)
  File "/home/federico/venvs/myenv/lib/python3.8/site-packages/albumentations/core/serialization.py", line 178, in from_dict
    args["transforms"] = [from_dict({"transform": t}, nonserializable=nonserializable) for t in args["transforms"]]
  File "/home/federico/venvs/myenv/lib/python3.8/site-packages/albumentations/core/serialization.py", line 178, in <listcomp>
    args["transforms"] = [from_dict({"transform": t}, nonserializable=nonserializable) for t in args["transforms"]]
  File "/home/federico/venvs/myenv/lib/python3.8/site-packages/albumentations/core/serialization.py", line 176, in from_dict
    cls = SERIALIZABLE_REGISTRY[shorten_class_name(name)]
KeyError: 'ToRGB'
```

## Expected behavior
The `ToRGB` transform should be deserialized.

## Environment

 - Albumentations version (e.g., 0.1.8): 1.3.0
 - Python version (e.g., 3.7): 3.8.10
 - OS (e.g., Linux): Ubuntu 20.04.4 LTS
 - How you installed albumentations (`conda`, `pip`, source): pip

**Comment by domef** [comment]
I just found out that the `ToRGB` has been merged on master with this PR https://github.com/albumentations-team/albumentations/pull/1323 but the last version of albumentations on pypi is older. However the documentations https://albumentations.ai/docs/ says that it refers to version 1.3.0 even if it actually refers to the master branch.

**Comment by ternaus** [comment]
As of Version 1.4.1 everything works:

```python
In [1]: import albumentations as A

In [2]: d = {
   ...:     "__version__": "1.3.0",
   ...:     "transform": {
   ...:         "__class_fullname__": "Compose",
   ...:         "additional_targets": {},
   ...:         "p": 1.0,
   ...:         "transforms": [
   ...:             {
   ...:                 "__class_fullname__": "albumentations.augmentations.transforms.ToRGB",
   ...:                 "p": 1.0,
   ...:             }
   ...:         ],
   ...:     },
   ...: }

In [3]: A.from_dict(d)
Out[3]:
Compose([
  ToRGB(always_apply=True, p=1.0),
], p=1.0, bbox_params=None, keypoint_params=None, additional_targets={}, is_check_shapes=True)
```

**Comment by ternaus** [comment]
@domef would you consider becoming a sponsor? 

https://github.com/sponsors/albumentations-team
