### ISSUE TITLE
ValueError in blur transforms

### ISSUE THREAD

**Issue by mohamad-hasan-sohan-ajini** [albumentations-team/albumentations#1456]
## 🐛 Bug

I get the `ValueError` while applying blur transform

## To Reproduce

Setting `image_path` and running the following snippet:
```
import albumentations as A
import cv2
from albumentations.pytorch import ToTensorV2

transforms = A.Compose(
    [
        A.MedianBlur(p=1.),
        A.Normalize(),
        ToTensorV2(),
    ]
)

image = cv2.imread(image_path, cv2.IMREAD_COLOR)
image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
transformed = transforms(image=image)
```

cause some error like:

```Traceback (most recent call last):
  File "/home/aj/repo/deep_fashion_2/data.py", line 130, in <module>
    image, bboxes, keypoints, classes, visibility = ds[0]
                                                    ~~^^^
  File "/home/aj/repo/deep_fashion_2/data.py", line 100, in __getitem__
    transformed = self._transforms(
                  ^^^^^^^^^^^^^^^^^
  File "/home/aj/repo/deep_fashion_2/venv/lib/python3.11/site-packages/albumentations/core/composition.py", line 205, in __call__
    data = t(**data)
           ^^^^^^^^^
  File "/home/aj/repo/deep_fashion_2/venv/lib/python3.11/site-packages/albumentations/core/transforms_interface.py", line 102, in __call__
    params = self.get_params()
             ^^^^^^^^^^^^^^^^^
  File "/home/aj/repo/deep_fashion_2/venv/lib/python3.11/site-packages/albumentations/augmentations/blur/transforms.py", line 44, in get_params
    return {"ksize": int(random.choice(np.arange(self.blur_limit[0], self.blur_limit[1] + 1, 2)))}
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/random.py", line 369, in choice
    if not seq:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

## Expected behavior

No error

## Environment

 - Albumentations version (e.g., 0.1.8): 1.3.0
 - Python version (e.g., 3.7): 3.11
 - OS (e.g., Linux): Ubuntu 20.04/22.04
 - How you installed albumentations (`conda`, `pip`, source): pip and source
 - Any other relevant information:

**Comment by Dipet** [comment]
Can not reproduce the problem
```python
import albumentations as A
import cv2
from albumentations.pytorch import ToTensorV2
import numpy as np

transforms = A.Compose(
    [
        A.MedianBlur(p=1.),
        A.Normalize(),
        ToTensorV2(),
    ]
)

image = np.empty([100, 100, 3], dtype=np.uint8)
image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
transformed = transforms(image=image)
```

**Comment by mohamad-hasan-sohan-ajini** [comment]
```(venv) aj@aj-laptop:~/repo/deep_fashion_2$ ipython
Python 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.14.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %cpaste
Pasting code; enter '--' alone on the line to stop or use Ctrl-D.
:import albumentations as A
import cv2
from albumentations.pytorch import ToTensorV2
import numpy as np

transforms = A.Compose(
    [
        A.MedianBlur(p=1.),
        A.Normalize(),
        ToTensorV2(),
    ]
)

image = np.empty([100, 100, 3], dtype=np.uint8)
image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
transformed = transforms(image=image):::::::::::::::
:--
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[1], line 16
     14 image = np.empty([100, 100, 3], dtype=np.uint8)
     15 image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
---> 16 transformed = transforms(image=image)

File ~/repo/deep_fashion_2/venv/lib/python3.11/site-packages/albumentations/core/composition.py:205, in Compose.__call__(self, force_apply, *args, **data)
    202     p.preprocess(data)
    204 for idx, t in enumerate(transforms):
--> 205     data = t(**data)
    207     if check_each_transform:
    208         data = self._check_data_post_transform(data)

File ~/repo/deep_fashion_2/venv/lib/python3.11/site-packages/albumentations/core/transforms_interface.py:102, in BasicTransform.__call__(self, force_apply, *args, **kwargs)
     99     return kwargs
    101 if (random.random() < self.p) or self.always_apply or force_apply:
--> 102     params = self.get_params()
    104     if self.targets_as_params:
    105         assert all(key in kwargs for key in self.targets_as_params), "{} requires {}".format(
    106             self.__class__.__name__, self.targets_as_params
    107         )

File ~/repo/deep_fashion_2/venv/lib/python3.11/site-packages/albumentations/augmentations/blur/transforms.py:44, in Blur.get_params(self)
     43 def get_params(self) -> Dict[str, Any]:
---> 44     return {"ksize": int(random.choice(np.arange(self.blur_limit[0], self.blur_limit[1] + 1, 2)))}

File /usr/lib/python3.11/random.py:369, in Random.choice(self, seq)
    367 def choice(self, seq):
    368     """Choose a random element from a non-empty sequence."""
--> 369     if not seq:
    370         raise IndexError('Cannot choose from an empty sequence')
    371     return seq[self._randbelow(len(seq))]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [2]: A.__version__
Out[2]: '1.3.0'

In [3]: 
```

Here comes the full error log that I get when running your snippet. Did you run it on python3.11 and albumentations=1.3.0?

**Comment by Dipet** [comment]
Try to update python. In python3.11.3 everything works fine.
It looks like you are using one of the very first versions of python3.11 and it is not stable.

**Comment by mohamad-hasan-sohan-ajini** [comment]
It fades the error away.
Thanks @Dipet
