### ISSUE TITLE
Albumentation causes memory error (OOM) when used with Ray and Tensorflow

### ISSUE THREAD

**Issue by basnetr** [albumentations-team/albumentations#1475]
## 🐛 Bug

Albumentation causes memory error (OOM) when used in AWS instance with Tensorflow 2.8.4 and Ray 2.5.0

## To Reproduce

```
transforms_list = []
transforms_list.append(A.OneOf([
    A.Affine(
            scale=1.0,
            translate_percent=0,
            rotate=0,
            shear=(-10, 10), 
            mode=0,
            cval=(123, 117, 104),
            p=1),
    A.Perspective(scale=(0.05, 0.0)),
                  fit_output=True, 
                  keep_size=True, 
                  pad_mode=0,
                  pad_val=(123, 117, 104),
                  p=1),
], p=value.get('probability', 0.5)))
transforms_list.append(A.PadIfNeeded(
        min_height=224, 
        min_width=224, 
        border_mode=0, 
        value=(123, 117, 104)))

transforms = A.Compose( 
    transforms_list, 
    bbox_params = A.BboxParams( 
        format = 'pascal_voc', 
        label_fields = ['bbox_classes'],
        min_area = 0
    ),
    keypoint_params=A.KeypointParams(
        format="xy", 
        label_fields=["keypoints_classes"]
    )
)

def augmentation_function(image, boxes, keypoints, labels):
    data = {"image": image, 
            "bboxes": boxes, "bbox_classes": labels, 
            "keypoints": xy_keypoints, "keypoints_classes": keypoints_label}
    transformed_data = transforms(**data)
    transformed_image  = np.array(transformed_data["image"], dtype=np.float32)
    transformed_boxes  = np.array(transformed_data["bboxes"], dtype=np.float32)
    transformed_labels = np.array(transformed_data["bbox_classes"], dtype=np.int64)  
    transformed_keypoints = np.expand_dims(transformed_keypoints, axis=0)
    return transformed_image, transformed_boxes, transformed_keypoints, transformed_labels

[aug_img, aug_box, aug_kpt, aug_lbl] = tf.numpy_function(augmentation_function, 
                                                    [image, boxes, keypoints, labels], 
                                                    [tf.float32, tf.float32, tf.float32, tf.int64])
```

## Expected behavior
When this part of code is run inside a Ray Cluster, the worker (node) crashes with following error [Without Albumentations augmentation no such error is seen]:
```
2023-06-29 17:04:38,272	WARNING worker.py:1829 -- The node with node id: e2755142e768fbb5c145707423d7b751e390ca60c35ecbc62d0b9be3 and address: 10.11.68.181 and node name: 10.11.68.181 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a 	(1) raylet crashes unexpectedly (OOM, preempted node, etc.) 
	(2) raylet has lagging heartbeats due to slow network or busy workload.
(automl_entry pid=5166) 2023-06-29 17:04:38,275	ERROR trial_runner.py:980 -- Trial Trial_7787bf1c: Error processing event.
(automl_entry pid=5166) ray.tune.error._TuneNoNextExecutorEventError: Traceback (most recent call last):
(automl_entry pid=5166)   File "/opt/conda/envs/automl/lib/python3.9/site-packages/ray/tune/execution/ray_trial_executor.py", line 989, in get_next_executor_event
(automl_entry pid=5166)     future_result = ray.get(ready_future)
(automl_entry pid=5166)   File "/opt/conda/envs/automl/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
(automl_entry pid=5166)     return func(*args, **kwargs)
(automl_entry pid=5166)   File "/opt/conda/envs/automl/lib/python3.9/site-packages/ray/_private/worker.py", line 2277, in get
(automl_entry pid=5166)     raise value
(automl_entry pid=5166) ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
(automl_entry pid=5166) 	class_name: ImplicitFunc
(automl_entry pid=5166) 	actor_id: 2804ccbd3a9710efb8bf9f3103000000
(automl_entry pid=5166) 	pid: 4358
(automl_entry pid=5166) 	namespace: 5ff84007-7b98-4cf8-8248-2534349c9919
(automl_entry pid=5166) 	ip: 10.11.68.181
(automl_entry pid=5166) The actor is dead because its node has died. Node Id: e2755142e768fbb5c145707423d7b751e390ca60c35ecbc62d0b9be3
```

## Environment

 - Albumentations version: 1.3.0
 - Python version): 3.9.13
 - Machine: AWS g4dn.2xlarge - Ubuntu
 - How you installed albumentations: pip
 - Any other relevant information: Ran on Ray worker (node) [https://docs.ray.io/en/latest/]

## Additional context
When Albumentations is run on cluster with ray tune, it causes workers to crash because of high memory consumption.

**Comment by Dipet** [comment]
Unfortunately, without a reproducible example I can not help with this. Please provide an example of data : image shapes, bboxes, labels, keypoints
