### ISSUE TITLE
"Albumentations: Rare Mask Alteration During Image and Mask Resizing for Semantic Segmentation

### ISSUE THREAD

**Issue by Houssem-kikleo** [albumentations-team/albumentations#1506]
### Description
I encountered a bug while using the Albumentations library for data preprocessing. During the resizing of images and masks for semantic segmentation, I observed rare instances where the mask gets altered unexpectedly.

### To Reproduce

1. Use the `A.geometric.resize.Resize(height=self.resize_height, width=self.resize_width)` function to resize images and masks.
2. Load specific images and masks that trigger the issue.
3. Observe the output, especially the unique class IDs of the transformed masks.
4. There's an assertion in the code to ensure the transformed mask retains the same class IDs before and after the resize operation.

### code : 
```python
class SemanticSegmentationDataset(Dataset):

    """
    Dataset class for loading and processing semantic segmentation data.

    Args:
        images_paths: List of paths to image files.
        masks_paths: List of paths to mask files.
        resize_height: Desired resized image height (optional).
        resize_width: Desired resized image width (optional).
        normalize_mean: Mean values for normalization (optional).
        normalize_std: Standard deviation values for normalization (optional).
    """

    def __init__(self, images_paths, masks_paths, resize_height=None, resize_width=None, normalize_mean=None, normalize_std=None):
        super().__init__()

        # Store image and mask paths
        self.images_paths = images_paths
        self.masks_paths = masks_paths

        # Store resizing and normalization parameters
        self.resize_height = resize_height
        self.resize_width = resize_width
        self.normalize_mean = normalize_mean
        self.normalize_std = normalize_std

        # Create transformation pipelines for images and masks
        self.preprocess = self._get_preprocess_pipeline()

    def _get_preprocess_pipeline(self):
        """
        Get image and mask transformation pipeline based on provided parameters.

        Returns:
            albumentations.Compose: Image and mask transformation pipeline.
        """

        # Define custom resizing functions for image and mask
        # def custom_resize(image, mask):
        #     if self.resize_height and self.resize_width:
        #         image = A.resize(image=image, height=self.resize_height, width=self.resize_width, interpolation=cv2.INTER_LINEAR)
        #         mask = A.resize(image=mask, height=self.resize_height, width=self.resize_width, interpolation=cv2.INTER_NEAREST)
        #     return image, mask

        # Define Albumentations transformations
        preprocess_list = []
        # transforms_list.append(A.Lambda(image=custom_resize))
        if self.resize_height and self.resize_width:
            preprocess_list.append(A.geometric.resize.Resize(height=self.resize_height, width=self.resize_width))  # Resize images

        # if self.normalize_mean and self.normalize_std:
        #     preprocess_list.append(A.Normalize(mean=self.normalize_mean, std=self.normalize_std))  # Normalize images

        preprocess_list.append(A.pytorch.ToTensorV2())

        # Create an Albumentations pipeline
        transform = A.Compose(preprocess_list)

        return transform

    def __len__(self):
        """
        Retrieve the number of images in the dataset.

        Returns:
            int: Number of images in the dataset.
        """

        return len(self.images_paths)

    def __getitem__(self, idx: int):
        """
        Retrieve an item from the dataset by index.

        Args:
            idx (int): Index of the item to retrieve.

        Returns:
            Tuple: A tuple containing the transformed image and mask.
        """

        # Load the image and mask from their respective paths
        try:
            image_path = self.images_paths[idx]
            mask_path = self.masks_paths[idx]
        except IndexError:
            raise IndexError(f"Index {idx} is out of bounds.")

        # Open and read the image and mask
        image = read_image(image_path)
        mask = read_image(mask_path)
        # image_info(mask, unique=True)

        # Apply transformations using the respective pipelines
        # image_info(mask)

        preprocess = self.preprocess(image=image, mask=mask)
        transformed_image = preprocess["image"]
        transformed_mask = preprocess["mask"]
        # print(transformed_mask)

        print(image_path)
        print(f"mask before resize  : {np.unique(mask)}")
        print(f"mask after resize   : {np.unique(transformed_mask.numpy())}")

        assert (np.unique(transformed_mask.numpy()) == np.unique(mask)).all(), "ERROR transformation"
        # image_info(transformed_mask.numpy(), unique=True)

        # transform to long (int 64) if you need one hot encoding function(pytorch version) in loss function
        transformed_mask = transformed_mask.long()
        return transformed_image, transformed_mask
``` 

### Expected behavior
I expected that the resized masks would retain the same class IDs as the original masks consistently. However, in rare cases, the mask alterations were observed.

### output 

```bash 
##################################################
# START TRAINING
##################################################
  0%|                                                                                                                                                                            | 0/250 [00:00<?, ?epoch/s/media/ssd2/Supervisely_data/kikleo_data/ML/TRAY-sematic-seg/Train_V0/images/chaplin_2022_01_31_12:09:30_top:40_left:250.jpeg                                                          | 0/1 [00:00<?, ?it/s]
mask before resize  : [ 0 12 20 24 25 31 32 33 37]
mask after resize   : [ 0 20 24 25 31 32 33 37]
Processing:   0%|                                                                                                                                                                     | 0/1 [00:00<?, ?it/s]
  0%|                                                                                                                                                                            | 0/250 [00:00<?, ?epoch/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/houssem/projects/supervisely/apps/ML/train.py", line 245, in <module>
    main(args)
  File "/home/houssem/projects/supervisely/apps/ML/train.py", line 219, in main
    seg_model.train(train_dataloader=train_dataloader, validation_data_loader=val_dataloader, batch_size=train_batch_size, epochs=nb_epochs)
  File "/home/houssem/projects/supervisely/apps/ML/src/segmentation/models/base.py", line 90, in train
    for i, (data, target) in enumerate(tqdm(train_dataloader)):
  File "/home/houssem/mambaforge/envs/pytorch/lib/python3.11/site-packages/supervisely/task/progress.py", line 446, in __iter__
    yield from super().__iter__()
  File "/home/houssem/mambaforge/envs/pytorch/lib/python3.11/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/home/houssem/mambaforge/envs/pytorch/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/houssem/mambaforge/envs/pytorch/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/houssem/mambaforge/envs/pytorch/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/houssem/mambaforge/envs/pytorch/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/houssem/projects/supervisely/apps/ML/src/data/data_segmentation.py", line 222, in __getitem__
    assert (np.unique(transformed_mask.numpy()) == np.unique(mask)).all(), "ERROR transformation"
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: operands could not be broadcast together with shapes (8,) (9,)
```

### Attempted Solution
I attempted to mitigate the issue by commenting out the resize function _get_preprocess_pipeline and used the cv2.resize function directly. This alternative method seems to work effectively, without causing unexpected changes in the masks.

### My new code : 
``` python
class SemanticSegmentationDataset(Dataset):

    """
    Dataset class for loading and processing semantic segmentation data.

    Args:
        images_paths: List of paths to image files.
        masks_paths: List of paths to mask files.
        resize_height: Desired resized image height (optional).
        resize_width: Desired resized image width (optional).
        normalize_mean: Mean values for normalization (optional).
        normalize_std: Standard deviation values for normalization (optional).
    """

    def __init__(self, images_paths, masks_paths, resize_height=None, resize_width=None, normalize_mean=None, normalize_std=None):
        super().__init__()

        # Store image and mask paths
        self.images_paths = images_paths
        self.masks_paths = masks_paths

        # Store resizing and normalization parameters
        self.resize_height = resize_height
        self.resize_width = resize_width
        self.normalize_mean = normalize_mean
        self.normalize_std = normalize_std

        # Create transformation pipelines for images and masks
        self.preprocess = self._get_preprocess_pipeline()

    def _get_preprocess_pipeline(self):
        """
        Get image and mask transformation pipeline based on provided parameters.

        Returns:
            albumentations.Compose: Image and mask transformation pipeline.
        """

        # Define Albumentations transformations
        preprocess_list = []
        # transforms_list.append(A.Lambda(image=custom_resize))
        # if self.resize_height and self.resize_width:
        #     preprocess_list.append(A.geometric.resize.Resize(height=self.resize_height, width=self.resize_width))  # Resize images

        if self.normalize_mean and self.normalize_std:
            preprocess_list.append(A.Normalize(mean=self.normalize_mean, std=self.normalize_std))  # Normalize images

        preprocess_list.append(A.pytorch.ToTensorV2())

        # Create an Albumentations pipeline
        transform = A.Compose(preprocess_list)

        return transform

    def __len__(self):
        """
        Retrieve the number of images in the dataset.

        Returns:
            int: Number of images in the dataset.
        """

        return len(self.images_paths)

    def __getitem__(self, idx: int):
        """
        Retrieve an item from the dataset by index.

        Args:
            idx (int): Index of the item to retrieve.

        Returns:
            Tuple: A tuple containing the transformed image and mask.
        """

        # Load the image and mask from their respective paths
        try:
            image_path = self.images_paths[idx]
            mask_path = self.masks_paths[idx]
        except IndexError:
            raise IndexError(f"Index {idx} is out of bounds.")

        # Open and read the image and mask
        image = read_image(image_path)
        mask = read_image(mask_path)
        # image_info(mask, unique=True)

        # Apply transformations using the respective pipelines
        # image_info(mask)

        if self.resize_height and self.resize_width:
            resized_image = cv2.resize(image, dsize=(self.resize_height, self.resize_width), interpolation=cv2.INTER_LINEAR)
            resized_mask = cv2.resize(mask, dsize=(self.resize_height, self.resize_width), interpolation=cv2.INTER_NEAREST)
        else:
            resized_image = image
            resized_mask = mask

        preprocess = self.preprocess(image=resized_image, mask=resized_mask)
        transformed_image = preprocess["image"]
        transformed_mask = preprocess["mask"]

        print(image_path)
        print(f"mask before resize  : {np.unique(resized_mask)}")
        print(f"mask after resize   : {np.unique(transformed_mask.numpy())}")

        assert (np.unique(transformed_mask.numpy()) == np.unique(resized_mask)).all(), "ERROR transformation"
        # image_info(transformed_mask.numpy(), unique=True)

        # transform to long (int 64) if you need one hot encoding function(pytorch version) in loss function
        transformed_mask = transformed_mask.long()
        print(transformed_image.size())
        return transformed_image, transformed_mask
```

### Additional Notes
The unexpected modification of masks during the resizing process occurs very rarely. Seeking insights or potential reasons for this behavior and exploring why the alternative approach using cv2.resize resolves the issue successfully.

This new method utilizing CV2 works well, but I'm surprised that this issue of mask alteration occurs very infrequently.

## Environment

 - Albumentations          |     1.3.1    |          pyhd8ed1ab_0    conda-forge
 - Python version            |     3.11.7  |        hab00c5b_0_cpython    conda-forge
 - OS :                                  Ubuntu 18.04.6 LTS
 - How you installed albumentations : conda-forge using Mamba
 - Open cv
 - Any other relevant information: 
   - libopencv            |     4.8.1     |      py311h1c4e2e0_5    conda-forge
   - opencv                |    4.8.1      |    py311hf4f9f61_5    conda-forge
   - opencv-python      |       4.8.1.78     |            pypi_0    pypi
   - py-opencv             |    4.8.1      |     py311hbeafb31_5    conda-forge

**Comment by ternaus** [comment]
I need a minimal example that could reproduce the issue. Closing for now, will be happy to reopen with more information.
