### ISSUE TITLE
check_for_updates error

### ISSUE THREAD

**Issue by prj-jxust** [albumentations-team/albumentations#1737]
## Describe the bug

check_for_updates() This function often crashes. The try except syntax does not prevent all errors from occurring.Now when running code, sometimes it can run normally and sometimes it will report an error.Unable to adapt to complex network environments and proxy situations.

### To Reproduce

1. Environment (windows 11, Python 3.8, Albumentations 1.4.7)
2. Sample code that produces the bug.
```
import os
import cv2
import albumentations as A
import numpy as np
import random
import math


class OfflineDataAugmentation:

    def __init__(self):
        self.transform = A.Compose([
            A.RandomCrop(width=256, height=256),
            #A.HorizontalFlip(p=0.5),
            #A.RandomBrightnessContrast(p=0.2),
            A.Affine(scale=(0.8, 1.2), translate_percent=0.3, rotate=(-4, 4), p=0.5)
        ])

    def run(self, image):
        return self.transform(image=image)

if __name__ == "__main__":
    img_dir = r'C:\Users\AI\Desktop\ng\ng\3579'
    save_dir = r'C:\Users\AI\Desktop\testtest'
    img_name_list = os.listdir(img_dir)
    ODA = OfflineDataAugmentation()
    for name in img_name_list:
        img = cv2.imread(os.path.join(img_dir, name))
        img_ = ODA.run(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        cv2.imwrite(os.path.join(save_dir, name), cv2.cvtColor(img_['image'], cv2.COLOR_RGB2BGR))
```
3. Any error messages or incorrect outputs.
```
Traceback (most recent call last):
  File "D:\AiService\JX2750AiTrainingSystem\data\augment.py", line 4, in <module>
    import albumentations as A
  File "C:\Users\AI\AppData\Roaming\Python\Python38\site-packages\albumentations\__init__.py", line 11, in <module>
    check_for_updates()
  File "C:\Users\AI\AppData\Roaming\Python\Python38\site-packages\albumentations\check_version.py", line 23, in check_for_updates
    data = response.read()
  File "C:\Users\AI\.conda\envs\yolov8_cls\lib\http\client.py", line 472, in read
    s = self._safe_read(self.length)
  File "C:\Users\AI\.conda\envs\yolov8_cls\lib\http\client.py", line 613, in _safe_read
    data = self.fp.read(amt)
  File "C:\Users\AI\.conda\envs\yolov8_cls\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\AI\.conda\envs\yolov8_cls\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\AI\.conda\envs\yolov8_cls\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
```
### Expected behavior

Program run successfully

### Actual behavior

Program error

### Additional context

Add any other context about the problem here, like links to similar issues or possible solutions you've found.

**Comment by ternaus** [comment]
Should be fixed in https://github.com/albumentations-team/albumentations/pull/1725/files

You may try to check if install latest version from the repo with:

```bash
pip install -U git+https://github.com/albumentations-team/albumentations
```

But I am going to doublecheck.

If installing directly from repo is not an option, let me know => will release out of schedule hotfix version.
