### ISSUE TITLE
Check_for_updates TimeoutError: The read operation timed out

### ISSUE THREAD

**Issue by Qolorerr** [albumentations-team/albumentations#1751]
### Description of error

Hello

I was testing the model parameters as usual, when I received a strange error. As I understand it, in one of the epochs albumentations tried to check for updates on the Internet. I assume that at that moment there was a problem with wi-fi, which could have caused it. 

Is it possible to somehow disable checking for updates in the settings so as not to receive such an error at the wrong time?

### Enviroment

Python 3.10.13
Albumentaions 1.4.7
Hydra 1.3.2
Torch 2.1.1

### Error producing code

`import albumentations`

### Error message

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Qolorer\.conda\envs\torch\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Qolorer\.conda\envs\torch\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "D:\Programs\Projects\People-segmentation\src\dataloaders\__init__.py", line 1, in <module>
    from .cityscapes import CityscapesDataset
  File "D:\Programs\Projects\People-segmentation\src\dataloaders\cityscapes.py", line 8, in <module>
    from src.base import BaseDataset
  File "D:\Programs\Projects\People-segmentation\src\base\__init__.py", line 1, in <module>
    from .base_dataset import BaseDataset
  File "D:\Programs\Projects\People-segmentation\src\base\base_dataset.py", line 4, in <module>
    import albumentations
  File "C:\Users\Qolorer\.conda\envs\torch\lib\site-packages\albumentations\__init__.py", line 11, in <module>
    check_for_updates()
  File "C:\Users\Qolorer\.conda\envs\torch\lib\site-packages\albumentations\check_version.py", line 23, in check_for_updates
    data = response.read()
  File "C:\Users\Qolorer\.conda\envs\torch\lib\http\client.py", line 482, in read
    s = self._safe_read(self.length)
  File "C:\Users\Qolorer\.conda\envs\torch\lib\http\client.py", line 631, in _safe_read
    data = self.fp.read(amt)
  File "C:\Users\Qolorer\.conda\envs\torch\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Qolorer\.conda\envs\torch\lib\ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Qolorer\.conda\envs\torch\lib\ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out
Validation:   0%|          | 0/34 [00:18<?, ?it/s]
Error executing job with overrides: []
Traceback (most recent call last):
  File "C:\Users\Qolorer\.conda\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 1132, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\Qolorer\.conda\envs\torch\lib\multiprocessing\queues.py", line 114, in get
    raise Empty
_queue.Empty
```

**Comment by ternaus** [comment]
Fixed in version 1.4.8
