### ISSUE TITLE
AttributeError: 'Albumentations' object has no attribute 'contains_spatial'

### ISSUE THREAD

**Issue by AITIS-AnveshaMishra** [albumentations-team/albumentations#1793]
## I have applied spatial transformations in my yaml file but I keep getting this error : 
AttributeError: 'Albumentations' object has no attribute 'contains_spatial'

### Without augmentations the code is working fine. Here is my yaml file with the transformations : 
train: ../dataset_harness_cv2_balanced_subset/images/train
val: ../dataset_harness_cv2_balanced_subset/images/val
test: ../dataset_harness_cv2_balanced_subset/images/test

nc: 2
names: ['harness unhooked', 'harness hooked']

# Augmentations
augmentation:
  flipud: 0.5
  flipud: 0.5
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  rotate: 0.01
  scale: 0.5
  shear: 0.01
  perspective: 0.0
  translate: 0.1

### Full detailed error :
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "[/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308](https://38.80.122.115:43733/lab/tree/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py#line=307), in _worker_loop
    data = fetcher.fetch(index)
  File "[/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51](https://38.80.122.115:43733/lab/tree/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py#line=50), in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "[/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51](https://38.80.122.115:43733/lab/tree/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py#line=50), in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "[/opt/conda/lib/python3.10/site-packages/ultralytics/data/base.py", line 251](https://38.80.122.115:43733/lab/tree/opt/conda/lib/python3.10/site-packages/ultralytics/data/base.py#line=250), in __getitem__
    return self.transforms(self.get_image_and_label(index))
  File "[/opt/conda/lib/python3.10/site-packages/ultralytics/data/augment.py", line 75](https://38.80.122.115:43733/lab/tree/opt/conda/lib/python3.10/site-packages/ultralytics/data/augment.py#line=74), in __call__
    data = t(data)
  File "[/opt/conda/lib/python3.10/site-packages/ultralytics/data/augment.py", line 956](https://38.80.122.115:43733/lab/tree/opt/conda/lib/python3.10/site-packages/ultralytics/data/augment.py#line=955), in __call__
    if self.contains_spatial:
AttributeError: 'Albumentations' object has no attribute 'contains_spatial'

Please help me fix this error. Thank you in advance!

**Comment by ternaus** [comment]
Could you please provide an example of the code that reproduces the error?

And I think that it is about @ultralitycs and not @albumentations.

I would recommend to ask there: https://github.com/ultralytics/ultralytics

**Comment by AITIS-AnveshaMishra** [comment]
I was able to resolve it by making changes in the augment.py file where I supplied my own augmentations. Just substituted the following :
            T = [
                A.RandomRain(p=0.1),
                A.Rotate(limit=10, p=0.5),
                A.Blur(p=0.1),
                A.MedianBlur(p=0.1),
                A.ToGray(p=0.01),
                A.CLAHE(p=0.01),
                A.ImageCompression(quality_lower=75, p=0.0),
            ]
But I am sure there is a much neater way to do this without opening that file, I just don't know how yet!
Also yes I agree I can do this with ultralytics directly but was unable to find the right way to do it
