### ISSUE TITLE
 Transformation's IndexError on Empty Bounding Boxes List/ Array

### ISSUE THREAD

**Issue by CargoXZ** [albumentations-team/albumentations#1910]
## Describe the bug

In albumentations-1.4.14, running a transformation on an empty list of bounding boxes or a bounding box numpy array of shape [0,4] causes an IndexError. This error does not occur in albumentations-1.4.13.

My guess is that the error is caused by an improper usage of np.array() or a similar numpy function. np.array([]) returns a 1-D numpy array, whereas the correct way to convert an empty list to an empty 2-D numpy array of bounding boxes would be with a call to a function like np.zeros(shape=(0,4)). I suspect the empty bounding boxes list or array is being converted to a list, then back to a numpy array improperly at some point in the transformation.

I suspect this because calling np.array([])[:, [0,2]] on its own results in the same IndexError.

### To Reproduce

1. Environment: Ubuntu 22.04, Python 3.9.19, albumentations-1.4.14, numpy-1.26.4

2. Sample code that produces the bug.

```
import albumentations as A
import numpy as np

if __name__ == "__main__":
    transform = A.Compose(
        [A.ToFloat(), A.PadIfNeeded(min_height=256, min_width=256)],
        bbox_params=A.BboxParams(format="pascal_voc", label_fields=["labels"]),
    )
    image = np.zeros(shape=(256, 256))
    bboxes = []
    labels = []

    # Error also occurs if using an empty numpy array
    # bboxes = np.zeros(shape=(0, 4))
    # labels = np.zeros(shape=(0, ))

    # Error does not occur if bboxes is not empty
    # bboxes = [[10,10,20,20]]
    # labels = [1]

    result = transform(image=image, bboxes=bboxes, labels=labels)
```

3. Any error messages or incorrect outputs.

Error Message:
```
Traceback (most recent call last):
  File "<path to my script>/albumentations_bug_example.py", line 18, in <module>
       result = transform(image=image, bboxes=bboxes, labels=labels)
  File "<anaconda environment path>/lib/python3.9/site-packages/albumentations/core/composition.py", line 307, in __call__
       data = t(**data)
  File "<anaconda environment path>/lib/python3.9/site-packages/albumentations/core/transforms_interface.py", line 122, in __call__
       return self.apply_with_params(params, **kwargs)
  File "<anaconda environment path>/lib/python3.9/site-packages/albumentations/core/transforms_interface.py", line 140, in apply_with_params
       res[key] = target_function(arg, **params)
  File "<anaconda environment path>/lib/python3.9/site-packages/albumentations/augmentations/geometric/transforms.py", line 1470, in apply_to_bboxes
       bboxes_np = denormalize_bboxes(bboxes_np, rows, cols)
  File "<anaconda environment path>/lib/python3.9/site-packages/albumentations/core/bbox_utils.py", line 256, in denormalize_bboxes
       denormalized[:, [0, 2]] *= cols

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

**Comment by ternaus** [comment]
Thanks for the report. Will look tomorrow.

**Comment by ternaus** [comment]
@CargoXZ It was a good one.

Fixed.
