### ISSUE TITLE
PadIfNeeded throws error when no bounding box labels - regression from 1.4.13

### ISSUE THREAD

**Issue by Chris-hughes10** [albumentations-team/albumentations#1918]
## Describe the bug

When I try to run `LongestMaxSize` followed by `PadIfNeeded` for an image with no bounding box labels an error is raised. This is a regression from version 1.4.13

### To Reproduce

Environment (e.g., OS, Python version, Albumentations version, etc.)
OS: Linux
Python version: 3.12.5
Albumentations version:  1.4.14

Sample code that produces the bug.
```
import albumentations as A
import numpy as np

image_size=(640, 640)

transforms = [
        A.LongestMaxSize(max(image_size)),
        A.PadIfNeeded(
            image_size[0],
            image_size[1],
            border_mode=0,
            value=(114, 114, 114),
        ),
    ]
tfms = A.Compose(
        transforms,
        bbox_params=A.BboxParams(format="pascal_voc", label_fields=["labels"]),
    )

transformed = tfms(image=np.random.rand(3, 800, 500), bboxes=np.array([]), labels=np.array([]))
image = transformed["image"]
xyxy_bboxes = np.array(transformed["bboxes"])
class_ids = np.array(transformed["labels"])

print(image.shape)
```

Any error messages or incorrect outputs.

```
Traceback (most recent call last):
  File "/workspaces/object-detection-rl/src/explore/data/albumentations_bug.py", line 22, in <module>
    transformed = tfms(image=np.random.rand(3, 800, 500), bboxes=np.array([]), labels=np.array([]))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/core/lib/python3.12/site-packages/albumentations/core/composition.py", line 307, in __call__
    data = t(**data)
           ^^^^^^^^^
  File "/opt/conda/envs/core/lib/python3.12/site-packages/albumentations/core/transforms_interface.py", line 122, in __call__
    return self.apply_with_params(params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/core/lib/python3.12/site-packages/albumentations/core/transforms_interface.py", line 140, in apply_with_params
    res[key] = target_function(arg, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/core/lib/python3.12/site-packages/albumentations/augmentations/geometric/transforms.py", line 1470, in apply_to_bboxes
    bboxes_np = denormalize_bboxes(bboxes_np, rows, cols)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/core/lib/python3.12/site-packages/albumentations/core/bbox_utils.py", line 256, in denormalize_bboxes
    denormalized[:, [0, 2]] *= cols
    ~~~~~~~~~~~~^^^^^^^^^^^
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

### Expected behavior

An error is not raised and the transform is applied to the image, as in version 1.4.13

### Actual behavior

An error is raised

### Additional context

Add any other context about the problem here, like links to similar issues or possible solutions you've found.

**Comment by ternaus** [comment]
Thanks for the bug report.

The issue was fixed last week in https://github.com/albumentations-team/albumentations/pull/1911

But I did not release a new version to PyPI yet, as a lot of functionality was changed. 

Working on adding more tests. 

Hopefully by the end of the week will release a new version with all the fixes, including empty boxes to PyPI
