### ISSUE TITLE
TypeError with v1.4.15 and newer for masks augmentation

### ISSUE THREAD

**Issue by volks73** [albumentations-team/albumentations#1958]
## Description

The following error message is received when running augmentations with masks using Albumentations v1.4.15 and Albucore v0.0.15 or newer:

```
TypeError: masks must be list of numpy arrays
```

This was first observed in https://github.com/ultralytics/ultralytics/pull/6624#issuecomment-2381455402 and downgrading to Albumentations v1.4.14 was confirmed, https://github.com/ultralytics/ultralytics/pull/6624#issuecomment-2385943805.

#### Environment

- OS: Ubuntu amd64
- Python: v3.11
- Albumentations: v1.4.15 or newer

#### Sample Code

Snippet from https://github.com/ultralytics/ultralytics/pull/6624.

```python
    ...
            T = [
                A.Blur(p=0.01),
                A.MedianBlur(p=0.01),
                A.ToGray(p=0.01),
                A.CLAHE(p=0.01),
                A.RandomBrightnessContrast(p=0.0),
                A.RandomGamma(p=0.0),
                A.ImageCompression(quality_lower=75, p=0.0)]  # transforms
            bbox_params = A.BboxParams(format='yolo', label_fields=['class_labels', 'indices'])
            self.transform = A.Compose(T, bbox_params=bbox_params)
    ...

    def __call__(self, labels):
        """Generates object detections and returns a dictionary with detection results."""
        im = labels['img']
        cls = labels['cls']
        if len(cls):
            h, w = im.shape[:2]
            # Remember if instances are normalized before transform to restore later
            normalized = labels['instances'].normalized
            # Convert denormalized segments to masks
            labels['instances'].denormalize(w, h)
            masks = None
            if labels['instances'].segments.shape[0] > 0:
                masks = polygons2masks((h, w), labels['instances'].segments, color=1, downsample_ratio=1)
            labels['instances'].convert_bbox('xywh')
            labels['instances'].normalize(w, h)
            bboxes = labels['instances'].bboxes
            # TODO: add support for keypoints
            if self.transform and random.random() < self.p:
                new = self.transform(image=im,
                                     masks=masks,
                                     bboxes=bboxes,
                                     class_labels=cls,
                                     indices=np.arange(len(bboxes)))  # transformed
                labels['img'] = new['image']
                if len(new['class_labels']) > 0:  # skip update if no bbox in new im
                    labels['cls'] = np.array(new['class_labels'])
                    bboxes_new = np.array(new['bboxes'], dtype=np.float32)
                    if masks is None:
                        labels['instances'].update(bboxes=bboxes_new)
                    else:
                        masks_new = np.array(new['masks'])[new['indices']]  # use bbox indices to find matching masks
                        segments_new = masks2segments(masks_new, strategy='largest')
                        non_empty = [s.shape[0] != 0 for s in segments_new]  # find non empty segments
                        segments_out = [segment for segment, flag in zip(segments_new, non_empty) if flag]
                        bboxes_out = bboxes_new[non_empty]
                        if len(segments_out) > 0:
                            segments_out = resample_segments(segments_out)
                            segments_out = np.stack(segments_out, axis=0)
                            segments_out /= (w, h)
                        else:
                            segments_out = np.zeros((0, 1000, 2), dtype=np.float32)
                        labels['instances'].update(bboxes=bboxes_out, segments=segments_out)
                if normalized:
                    labels['instances'].normalize(w, h)
                else:
                    labels['instances'].denormalize(w, h)

        return labels
```

#### Error Messages

```
TypeError: masks must be list of numpy arrays
```

### Expected behavior

The expected behavior is for masks augmentations to work for v1.4.15 or newer identically to v1.4.14.

### Actual behavior

The actual behavior is the `TypeError` is returned for newer versions of Albumentations.

### Additional Context

It is possible the API was changed and the `masks` need to be in some other structure as a list. I played around with `tolist` and a list generator but I would still receive the error. I could not figure out the intended list collection that is expected for the masks. The output from the `ploygons2masks` function is a Numpy array of ndarrays. The type signature accepts a list or a Numpy array.

**Comment by volks73** [comment]
This is also possibly related https://github.com/albumentations-team/albucore/issues/35.

**Comment by ternaus** [comment]
Thanks, will look ASAP

**Comment by ternaus** [comment]
@volks73 

FIxed in https://github.com/albumentations-team/albumentations/pull/1960

**Comment by armanivers** [comment]
Not sure if it doesn't work for because of the way I updated the library or because of something else.

I put the two changed files composition,py and transforms_interface.py from the last commit (the fix) into python3.11/site-packages/albumentations/ and replaced them. Is this the wrong way to test the fix? If no, then the training leads to this error this time:

```
TypeError: unhashable type: 'numpy.ndarray'
```

with the following full output:

```
Ultralytics 8.3.4 🚀 Python-3.11.8 torch-2.4.1+cu121 CUDA:0 (Tesla V100-SXM2-16GB, 16144MiB)
engine/trainer: task=segment, mode=train, model=yolov8x-seg.pt, data=/myraid/YOLOv8_home/yolov8-wound-seg/config1.yaml, epochs=100, time=None, patience=100, batch=16, imgsz=512, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train2, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0, hsv_s=0, hsv_v=0, degrees=0, translate=0, scale=0, shear=0.0, perspective=0, flipud=0, fliplr=0, bgr=0, mosaic=0, mixup=0, copy_paste=0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0, crop_fraction=0, cfg=None, tracker=botsort.yaml, save_dir=runs/segment/train2
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments                     
  0                  -1  1      2320  ultralytics.nn.modules.conv.Conv             [3, 80, 3, 2]                 
  1                  -1  1    115520  ultralytics.nn.modules.conv.Conv             [80, 160, 3, 2]               
  2                  -1  3    436800  ultralytics.nn.modules.block.C2f             [160, 160, 3, True]           
  3                  -1  1    461440  ultralytics.nn.modules.conv.Conv             [160, 320, 3, 2]              
  4                  -1  6   3281920  ultralytics.nn.modules.block.C2f             [320, 320, 6, True]           
  5                  -1  1   1844480  ultralytics.nn.modules.conv.Conv             [320, 640, 3, 2]              
  6                  -1  6  13117440  ultralytics.nn.modules.block.C2f             [640, 640, 6, True]           
  7                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]              
  8                  -1  3   6969600  ultralytics.nn.modules.block.C2f             [640, 640, 3, True]           
  9                  -1  1   1025920  ultralytics.nn.modules.block.SPPF            [640, 640, 5]                 
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 12                  -1  3   7379200  ultralytics.nn.modules.block.C2f             [1280, 640, 3]                
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']          
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 15                  -1  3   1948800  ultralytics.nn.modules.block.C2f             [960, 320, 3]                 
 16                  -1  1    922240  ultralytics.nn.modules.conv.Conv             [320, 320, 3, 2]              
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 18                  -1  3   7174400  ultralytics.nn.modules.block.C2f             [960, 640, 3]                 
 19                  -1  1   3687680  ultralytics.nn.modules.conv.Conv             [640, 640, 3, 2]              
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]                           
 21                  -1  3   7379200  ultralytics.nn.modules.block.C2f             [1280, 640, 3]                
 22        [15, 18, 21]  1   5791731  ultralytics.nn.modules.head.Segment          [1, 32, 320, [320, 640, 640]] 
YOLOv8x-seg summary: 425 layers, 65,226,371 parameters, 65,226,355 gradients, 313.9 GFLOPs

Transferred 615/693 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLO11n...
WARNING ⚠️ yolo11n.pt appears to require 'dill', which is not in Ultralytics requirements.
AutoInstall will run now for 'dill' but this feature will be removed in the future.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official Ultralytics model, i.e. 'yolo predict model=yolov8n.pt'
requirements: Ultralytics requirement ['dill'] not found, attempting AutoUpdate...
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: dill in /opt/conda/lib/python3.11/site-packages (0.3.8)

requirements: AutoUpdate success ✅ 4.4s, installed 1 package: ['dill']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect

AMP: checks skipped ⚠️. Unable to load YOLO11n due to possible Ultralytics package modifications. Setting 'amp=True'. If you experience zero-mAP or NaN losses you can disable AMP with amp=False.
train: Scanning /myraid/YOLOv8_home/yolov8-wound-seg/dataset_kfold/cv/1/train/labels.cache... 648 images, 49 backgrounds, 0 corrupt: 100%|██████████| 648/648 [00:00<?, ?it/s]
Albumentations Version: 1.4.17
albumentations: ShiftScaleRotate(p=0.7, shift_limit_x=(-0.3, 0.3), shift_limit_y=(-0.3, 0.3), scale_limit=(0.0, 0.0), rotate_limit=(0, 0), interpolation=1, border_mode=0, value=0.0, mask_value=0.0, rotate_method='largest_box')
val: Scanning /myraid/YOLOv8_home/yolov8-wound-seg/dataset_kfold/cv/1/val/labels.cache... 162 images, 19 backgrounds, 0 corrupt: 100%|██████████| 162/162 [00:00<?, ?it/s]
Plotting labels to runs/segment/train2/labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 112 weight(decay=0.0), 123 weight(decay=0.0005), 122 bias(decay=0.0)
Image sizes 512 train, 512 val
Using 8 dataloader workers
Logging results to runs/segment/train2
Starting training for 100 epochs...

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], line 23
     21 initYaml(i)
     22 model = YOLO('yolov8x-seg.pt')
---> 23 model_results = model.train(data=os.path.join(ROOT_DIR, f'config{i}.yaml'), epochs=training_epochs, imgsz=512, batch=16, deterministic=True, plots=True,
     24                 close_mosaic = 0,
     25                 # disable built-in augmentation, instead use Albumentations Library
     26                 augment=False, hsv_h=0, hsv_s=0, hsv_v=0, degrees=0, translate=0, 
     27                 scale=0, shear=0.0, perspective=0, flipud=0, fliplr=0, bgr=0, 
     28                 mosaic=0, mixup=0, copy_paste=0, erasing=0, crop_fraction=0)
     29 results = model.val()
     31 print("\n" + "#" * 60)

File ~/yolov8/lib/python3.11/site-packages/ultralytics/engine/model.py:802, in Model.train(self, trainer, **kwargs)
    799     self.model = self.trainer.model
    801 self.trainer.hub_session = self.session  # attach optional HUB session
--> 802 self.trainer.train()
    803 # Update model and cfg after training
    804 if RANK in {-1, 0}:

File ~/yolov8/lib/python3.11/site-packages/ultralytics/engine/trainer.py:207, in BaseTrainer.train(self)
    204         ddp_cleanup(self, str(file))
    206 else:
--> 207     self._do_train(world_size)

File ~/yolov8/lib/python3.11/site-packages/ultralytics/engine/trainer.py:367, in BaseTrainer._do_train(self, world_size)
    365     pbar = TQDM(enumerate(self.train_loader), total=nb)
    366 self.tloss = None
--> 367 for i, batch in pbar:
    368     self.run_callbacks("on_train_batch_start")
    369     # Warmup

File ~/yolov8/lib/python3.11/site-packages/tqdm/std.py:1181, in tqdm.__iter__(self)
   1178 time = self._time
   1180 try:
-> 1181     for obj in iterable:
   1182         yield obj
   1183         # Update and possibly print the progressbar.
   1184         # Note: does not call self.update(1) for speed optimisation.

File ~/yolov8/lib/python3.11/site-packages/ultralytics/data/build.py:48, in InfiniteDataLoader.__iter__(self)
     46 """Creates a sampler that repeats indefinitely."""
     47 for _ in range(len(self)):
---> 48     yield next(self.iterator)

File ~/yolov8/lib/python3.11/site-packages/torch/utils/data/dataloader.py:630, in _BaseDataLoaderIter.__next__(self)
    627 if self._sampler_iter is None:
    628     # TODO(https://github.com/pytorch/pytorch/issues/76750)
    629     self._reset()  # type: ignore[call-arg]
--> 630 data = self._next_data()
    631 self._num_yielded += 1
    632 if self._dataset_kind == _DatasetKind.Iterable and \
    633         self._IterableDataset_len_called is not None and \
    634         self._num_yielded > self._IterableDataset_len_called:

File ~/yolov8/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1344, in _MultiProcessingDataLoaderIter._next_data(self)
   1342 else:
   1343     del self._task_info[idx]
-> 1344     return self._process_data(data)

File ~/yolov8/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1370, in _MultiProcessingDataLoaderIter._process_data(self, data)
   1368 self._try_put_index()
   1369 if isinstance(data, ExceptionWrapper):
-> 1370     data.reraise()
   1371 return data

File ~/yolov8/lib/python3.11/site-packages/torch/_utils.py:706, in ExceptionWrapper.reraise(self)
    702 except TypeError:
    703     # If the exception takes multiple arguments, don't try to
    704     # instantiate since we don't know how to
    705     raise RuntimeError(msg) from None
--> 706 raise exception

TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/username/yolov8/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/username/yolov8/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/yolov8/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/username/yolov8/lib/python3.11/site-packages/ultralytics/data/base.py", line 256, in __getitem__
    return self.transforms(self.get_image_and_label(index))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/yolov8/lib/python3.11/site-packages/ultralytics/data/augment.py", line 201, in __call__
    data = t(data)
           ^^^^^^^
  File "/tmp/ipykernel_2145/881088670.py", line 58, in __call__
    new = self.transform(image=im,
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/yolov8/lib/python3.11/site-packages/albumentations/core/composition.py", line 346, in __call__
    self.preprocess(data)
  File "/home/username/yolov8/lib/python3.11/site-packages/albumentations/core/composition.py", line 380, in preprocess
    p.preprocess(data)
  File "/home/username/yolov8/lib/python3.11/site-packages/albumentations/core/utils.py", line 125, in preprocess
    data = self.add_label_fields_to_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/yolov8/lib/python3.11/site-packages/albumentations/core/utils.py", line 184, in add_label_fields_to_data
    encoded_labels = encoder.fit_transform(data[label_field])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/yolov8/lib/python3.11/site-packages/albumentations/core/utils.py", line 60, in fit_transform
    self.fit(y)
  File "/home/username/yolov8/lib/python3.11/site-packages/albumentations/core/utils.py", line 48, in fit
    unique_labels = sorted(set(y))
                           ^^^^^^
TypeError: unhashable type: 'numpy.ndarray'
```

**Comment by ternaus** [comment]
Thanks, will take a look.

**Comment by ternaus** [comment]
@volks73 

Fixed in https://github.com/albumentations-team/albumentations/pull/1967

**Comment by volks73** [comment]
@ternaus I appreciate the quick response and effort to resolve this issue. I saw the release notes for v1.4.18:

>Several people reported issue with masks as list of numpy arrays, I guess it was fixed as a part of some other work as I cannot reproduce it. Just in case added tests for that case.

Is this comment related to this issue and were you able to ultimately not reproduce issue? I will try v1.4.18.

**Comment by volks73** [comment]
I updated my virtual environment to use the latest release with:

```sh
python3 -m pip install ---upgrade albucore albumentations
```

and I no longer receive the `TypeError`. This appears to have been resolved. Thank you!
