### ISSUE TITLE
[Feature request] Dropout does not modify bounding boxes

### ISSUE THREAD

**Issue by mennohofste** [albumentations-team/albumentations#2221]
I checked the pull request implementing bounding boxes modification [2], but found no mention of this feature. An original implementation [1] did include this feature, so it might have been omitted for a purpose I could not find.

## Feature description

In any dropout augmentation, when the only one side of the bounding box is affected, I expected that box to be trimmed.

### Motivation and context

If one side is fully covered by a dropout, then we cannot say with certainty that the object continues. In many cases it is then desirable to only label the visible part. Think of a cow partially standing behind a wall, in that case I would only label the visible part of the cow without making assumptions about the invisible part. For consistency, I think dropout should at least be _able_ to do the same.

This is generally not a problem with larger objects, as fully covering one side is quite unlikely, unless you use very large cutouts. However, with many small objects and GridDropout this happens quite often and therefore impacts results.

### Possible implementation

Looking at the code, I would expect it to be implemented in `apply_to_bboxes` in `BaseDropout` in the file `dropout/transforms.py`. After the bounding boxes are denormalized, it would be relatively easy to restrict the corner coordinates.

In Github issue [1], one of the contributers mentioned that an earlier prototype worked that way: "if only one side of box is affected by cutout mask, box is trimmed to reflect the actual non-masked area". Maybe there is still a better implementation floating around. 

[1] https://github.com/albumentations-team/albumentations/issues/995
[2] https://github.com/albumentations-team/albumentations/pull/1953

### Alternatives

I could re-implement this outside Albumentations; however, as I ran into this issue I thought maybe others would as well.

### Additional context

For illustration purposes, maybe not the best use case, but it gets the idea across. Imagine many more smaller objects.

<img width="1492" alt="Screenshot 2024-12-30 at 16 25 27" src="https://github.com/user-attachments/assets/3144dd83-f020-4aaf-845f-e324a5cb65e9" />

I am also willing to help with an implementation if there is an interest in this.

**Comment by ternaus** [comment]
Thank you, fixed

**Comment by mennohofste** [comment]
Thank you so much for the quick response. I tried to use it; however, it results in an error on my data.

```
Traceback (most recent call last):
  File "augmentation.py", line 49, in <module>
    main()
  File "augmentation.py", line 43, in main
    for (imgs_base, labels_base), (imgs_extra, labels_extra) in loader:
                                                                ^^^^^^
  File ".venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 757, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "data.py", line 39, in __getitem__
    transformed = self.transform(image=img, bboxes=boxes, labels=labels)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/albumentations/core/composition.py", line 441, in __call__
    data = t(**data)
           ^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/albumentations/core/transforms_interface.py", line 173, in __call__
    return self.apply_with_params(params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/albumentations/core/transforms_interface.py", line 198, in apply_with_params
    target_function(ensure_contiguous_output(arg), **params),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/albumentations/augmentations/dropout/transforms.py", line 87, in apply_to_bboxes
    filter_bboxes_by_holes(
  File ".venv/lib/python3.12/site-packages/albumentations/augmentations/dropout/functional.py", line 344, in filter_bboxes_by_holes
    return resize_boxes_to_visible_area(valid_boxes, hole_mask)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/albumentations/augmentations/dropout/functional.py", line 298, in resize_boxes_to_visible_area
    regions = np.array(
              ^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (102,) + inhomogeneous part.
```

The reason is that the regions are not always the same size, so putting them in a numpy array is not possible.

```python
    regions = np.array(
        [hole_mask[y_start:y_end, x_start:x_end] for x_start, y_start, x_end, y_end in zip(x1, y1, x2, y2)],
    )
```

Minimally reproducible test:

```python
        # Test case 5: Multiple boxes of different size that are visible
        (
            np.array([
                [0, 0, 3, 3], # Box 1: fully visible
                [5, 0, 9, 4], # Box 2: fully visible
            ]),
            np.zeros((10, 10), dtype=np.uint8),  # Full image visible
            np.array([
                [0, 0, 3, 3], # Box 1: unchanged
                [5, 0, 9, 4], # Box 2: unchanged
            ]),
        ),
```

As for the fix, I am not entirely sure what the best course of action is especially if you want to keep it vectorized. Maybe zero padding to the largest box size? Also not super elegant.

**Comment by ternaus** [comment]
Thanks, will look again
