### ISSUE TITLE
IAAPerspective and IAAPiecewiseAffine  bug: do_assert(x2 > x1)

### ISSUE THREAD

**Issue by apatsekin** [albumentations-team/albumentations#464]
## 🐛 Bug

Values of scale above certain threshold error out with imgaug exception:
```
Traceback (most recent call last):
  File "/Users/a/projects/test/iaaperspective_bug.py", line 21, in <module>
    augmented = aug_func(**album_format)
  File "/usr/local/lib/python3.7/site-packages/albumentations/core/composition.py", line 176, in __call__
    data = t(force_apply=force_apply, **data)
  File "/usr/local/lib/python3.7/site-packages/albumentations/imgaug/transforms.py", line 38, in __call__
    return super(BasicIAATransform, self).__call__(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 87, in __call__
    return self.apply_with_params(params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 100, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))
  File "/usr/local/lib/python3.7/site-packages/albumentations/imgaug/transforms.py", line 55, in apply_to_bboxes
    bboxes_t = deterministic_processor.augment_bounding_boxes([bboxes_t])[0].bounding_boxes
  File "/usr/local/lib/python3.7/site-packages/imgaug/augmenters/meta.py", line 688, in augment_bounding_boxes
    y2=y2
  File "/usr/local/lib/python3.7/site-packages/imgaug/imgaug.py", line 1524, in copy
    label=self.label if label is None else label
  File "/usr/local/lib/python3.7/site-packages/imgaug/imgaug.py", line 1259, in __init__
    do_assert(x2 > x1)
  File "/usr/local/lib/python3.7/site-packages/imgaug/imgaug.py", line 678, in do_assert
    raise AssertionError(str(message))
AssertionError: Assertion failed.
```

## To Reproduce

```
import albumentations, numpy as np

aug_func = albumentations.imgaug.transforms.IAAPerspective(scale=(0.13,0.15), #if this
                                                keep_size=True, always_apply=True,
                                                p=0.5)
aug_func = albumentations.Compose([aug_func], bbox_params=albumentations.BboxParams(format='pascal_voc',
                                                                 min_area=30.0,
                                                                 min_visibility=0.2,
                                                                 label_fields=['category_id']))

img = np.random.randint(0,254,(1000,1000,3),dtype=np.uint8)
gt_bbox = np.asarray([[352, 230, 352+242, 230+131],
                      [470, 239, 470+88, 239+69]]).astype(np.float32).tolist()
gt_classes = np.asarray([8, 4])


album_format = {'image': img,
                'bboxes': gt_bbox,
                'category_id': gt_classes}
while True:
    augmented = aug_func(**album_format)
```

**Same applies to IAAPiecewiseAffine (default params)**
```
import albumentations, numpy as np
print(albumentations.__version__)

aug_func = albumentations.imgaug.transforms.IAAPiecewiseAffine(always_apply=True)
aug_func = albumentations.Compose([aug_func], bbox_params=albumentations.BboxParams(format='pascal_voc',
                                                                 min_area=30.0,
                                                                 min_visibility=0.2,
                                                                 label_fields=['category_id']))

img = np.random.randint(0,254,(512,512,3),dtype=np.uint8)

while True:
    x1 = np.random.randint(0,511)
    y1 = np.random.randint(0,511)
    x2 = x1 + np.random.randint(1,512-x1)
    y2 = y1 + np.random.randint(1,512-y1)
    gt_bbox = np.asarray([[x1,y1,x2,y2]]).astype(np.float32).tolist()
    print(gt_bbox)
    gt_classes = np.asarray([8, 4])

    album_format = {'image': img,
                    'bboxes': gt_bbox,
                    'category_id': gt_classes}
    augmented = aug_func(**album_format)
    print(augmented['bboxes'])
```

## Environment

 - Albumentations version (e.g., 0.1.8): 0.4.2
 - Python version (e.g., 3.7): 3.7.4
 - OS (e.g., Linux): MacOS
 - How you installed albumentations (`conda`, `pip`, source): pip3
 - Any other relevant information:

**Comment by ternaus** [comment]
imgaug depencency removed.

Use Perspective and PiesewiseAffine, they should work correctly
