### ISSUE TITLE
Failed to serialize ImageCompression class with albumentations.core.serialization.save

### ISSUE THREAD

**Issue by ni4muraano** [albumentations-team/albumentations#532]
## To Reproduce

1. Wrap ImageCompression class with Compose
2. Save the compose in yaml format using albumentations.core.serialization.save
3. An error happens

Traceback (most recent call last):
  File "augmentation_yaml_creator.py", line 31, in <module>
    save(train_compose, '..' + os.sep + 'configs' + os.sep + 'train_augmentation.yaml', data_format='yaml')
  File "lib\site-packages\albumentations\core\serialization.py", line 128, in save
    dump_fn(transform_dict, f)
  File "lib\site-packages\yaml\__init__.py", line 306, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "lib\site-packages\yaml\__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "lib\site-packages\yaml\representer.py", line 27, in represent
    node = self.represent_data(data)
  File "lib\site-packages\yaml\representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "lib\site-packages\yaml\representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "lib\site-packages\yaml\representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "lib\site-packages\yaml\representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "lib\site-packages\yaml\representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "lib\site-packages\yaml\representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "lib\site-packages\yaml\representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "lib\site-packages\yaml\representer.py", line 199, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
  File "lib\site-packages\yaml\representer.py", line 92, in represent_sequence
    node_item = self.represent_data(item)
  File "lib\site-packages\yaml\representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "lib\site-packages\yaml\representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "lib\site-packages\yaml\representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "lib\site-packages\yaml\representer.py", line 58, in represent_data
    node = self.yaml_representers[None](self, data)
  File "lib\site-packages\yaml\representer.py", line 231, in represent_undefined
    raise RepresenterError("cannot represent an object", data)
yaml.representer.RepresenterError: ('cannot represent an object', <ImageCompressionType.JPEG: 0>)

## Expected behavior

yaml file which contains augmentation infi is created.
This error does not happen if I use JPEGCompression instead of ImageCompression.

## Environment

 - Albumentations version (e.g., 0.1.8): 0.4.3
 - Python version (e.g., 3.7): 3.7
 - OS (e.g., Linux): Windows10
 - How you installed albumentations (`conda`, `pip`, source): conda

## Code to reproduce the error
```
from albumentations import Compose
from albumentations.core.serialization import save
from albumentations.augmentations.transforms import ImageCompression

train_compose = Compose([
        ImageCompression(quality_lower=50, quality_upper=50, p=1.0),
    ])
save(train_compose, 'test.yaml', data_format='yaml')
```

**Comment by creafz** [comment]
@ni4muraano Fixed in https://github.com/albumentations-team/albumentations/commit/7658a91eeffe29ccb50403370bcadccb7e45fc0e. For now you need to install the latest version of the library from the master branch to get the fixed version.

**Comment by ni4muraano** [comment]
@creafz Thanks! I'll install the latest version.
