### ISSUE TITLE
Failed to apply RandomResizedCrop or RandomSizedCrop for augmentation in segmentation task

### ISSUE THREAD

**Issue by ipScore** [albumentations-team/albumentations#539]
```
Environment:
Centos 7.6 
Python 3.6.8
opencv-python 4.2.0.32
torch  1.4.0
albumentations 0.4.3
```

Hi, @Dipet Is there any suggested fix for this issue?
When I apply RandomResizedCrop or RandomSizedCrop for image augmentation as the following:
```
def augmentation(image, mask):

    original_height, original_width = image.shape[0], image.shape[1]
    augmented = Compose([
        # RandomSizedCrop(min_max_height=(450, 501), height=original_height, width=original_width, p=1),
        RandomResizedCrop(height=original_height, width=original_width, scale=(0.75, 0.95), p=1),])
    tf_sample = augmented(image=image, mask=mask)

    return tf_sample
```
It raised out:

```
Original Traceback (most recent call last):
  File "/gs/home/songkq/anaconda/envs/torchEnv/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/gs/home/songkq/anaconda/envs/torchEnv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/gs/home/songkq/anaconda/envs/torchEnv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/gs/home/songkq/workspace/pyroom/DeepLabHPC/dataloader/dataloader_update.py", line 49, in __getitem__
    sample = self.augmentation(image=image, mask=mask)
  File "/gs/home/songkq/workspace/pyroom/DeepLabHPC/dataloader/transform.py", line 62, in augmentation
    tf_sample = augmented(image=image, mask=mask[0, :, :])
  File "/gs/home/songkq/anaconda/envs/torchEnv/lib/python3.6/site-packages/albumentations/core/composition.py", line 176, in __call__
    data = t(force_apply=force_apply, **data)
  File "/gs/home/songkq/anaconda/envs/torchEnv/lib/python3.6/site-packages/albumentations/core/transforms_interface.py", line 87, in __call__
    return self.apply_with_params(params, **kwargs)
  File "/gs/home/songkq/anaconda/envs/torchEnv/lib/python3.6/site-packages/albumentations/core/transforms_interface.py", line 100, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))
  File "/gs/home/songkq/anaconda/envs/torchEnv/lib/python3.6/site-packages/albumentations/core/transforms_interface.py", line 223, in apply_to_mask
    return self.apply(img, **{k: cv2.INTER_NEAREST if k == "interpolation" else v for k, v in params.items()})
  File "/gs/home/songkq/anaconda/envs/torchEnv/lib/python3.6/site-packages/albumentations/augmentations/transforms.py", line 808, in apply
    return F.resize(crop, self.height, self.width, interpolation)
  File "/gs/home/songkq/anaconda/envs/torchEnv/lib/python3.6/site-packages/albumentations/augmentations/functional.py", line 70, in wrapped_function
    result = func(img, *args, **kwargs)
  File "/gs/home/songkq/anaconda/envs/torchEnv/lib/python3.6/site-packages/albumentations/augmentations/functional.py", line 200, in resize
    return resize_fn(img)
  File "/gs/home/songkq/anaconda/envs/torchEnv/lib/python3.6/site-packages/albumentations/augmentations/functional.py", line 180, in __process_fn
    img = process_fn(img, **kwargs)
TypeError: Expected Ptr<cv::UMat> for argument 'src'

```

**Comment by Dipet** [comment]
I can not reproduce this problem with code below.
```
np.random.seed(0)

img = np.random.randint(0, 256, [1000, 1000, 3], dtype=np.uint8)
mask = np.random.randint(0, 2, [1000, 1000, 3], dtype=np.uint8)

res = augmentation(img, mask)
img = res['image']
mask = res['mask']

print(img.shape, mask.shape)
```

Can you get example of code to reproduce this problem?

**Comment by albu** [comment]
everything have to be numpy arrays, I suppose you're using tf tensors

**Comment by ipScore** [comment]
Thanks. @albu @Dipet 
I ignore that the `dtype` of my mask is `bool`, which results in the problem. Instead, after converting dtype to be as `np.uint8`, everything is OK.
