### ISSUE TITLE
RandomShadow input type wrong

### ISSUE THREAD

**Issue by shamangary** [albumentations-team/albumentations#614]
## 🐛 Bug

Weather transformation. For RandomRain, RandomSnow, RandomSunFlare the inputs are just numpy uint8. However, RandomShadow does not allow the same input format.

## To Reproduce

```
albu_shadow = albu.RandomShadow(p=1, num_shadows_lower=1, num_shadows_upper=1, shadow_dimension=5, shadow_roi=(0, 0.5, 1, 1))

x_np = albu_shadow(image=x_np)['image']
```

Error:
```
TypeError: Expected Ptr<cv::UMat> for argument img
```

## Expected behavior
It should take the same uint8 numpy array as input.

## Environment

 - Albumentations version: 0.4.5
 - Python version: 3.7.6
 - OS (e.g., Linux): Linux
 - How you installed albumentations: pip

**Comment by Dipet** [comment]
Our library supports only `numpy.ndarray` images. But you use `cv.UMat`.

**Comment by shamangary** [comment]
Just to be clear. My input is np uint8 array. It does not take it.

**Comment by BloodAxe** [comment]
Please provide a minimal code snippet to reproduce the issue.

вт, 5 мая 2020 г. в 11:59 AM, Tsun-Yi Yang <notifications@github.com>:

**Comment by shamangary** [comment]
```
>>> import albumentations as albu
>>> albu_shadow = albu.RandomShadow(p=1, num_shadows_lower=1, num_shadows_upper=1, shadow_dimension=5, shadow_roi=(0, 0.5, 1, 1))
>>> import numpy as np
>>> x_np = np.array([2,3]).astype(np.uint8)
>>> x_np = albu_shadow(image=x_np)['image']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tsunyi/anaconda3/envs/pytorch/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 78, in __call__
    params_dependent_on_targets = self.get_params_dependent_on_targets(targets_as_params)
  File "/home/tsunyi/anaconda3/envs/pytorch/lib/python3.7/site-packages/albumentations/augmentations/transforms.py", line 2061, in get_params_dependent_on_targets
    height, width = img.shape[:2]
ValueError: not enough values to unpack (expected 2, got 1)
>>> 
```

**Comment by Dipet** [comment]
All works fine. In your example image has wrong shape. Try this:
```
import albumentations as albu

albu_shadow = albu.RandomShadow(p=1, num_shadows_lower=1, num_shadows_upper=1, shadow_dimension=5, shadow_roi=(0, 0.5, 1, 1))

import numpy as np

x_np = np.empty([100, 100, 3], dtype=np.uint8)
x_np = albu_shadow(image=x_np)['image']
```

**Comment by shamangary** [comment]
Sorry, let me reproduce what I get.
```
import torch
import numpy as np
import albumentations as albu

albu_shadow = albu.RandomShadow(p=1, num_shadows_lower=1, num_shadows_upper=1, shadow_dimension=5, shadow_roi=(0, 0.5, 1, 1))

x = torch.rand(1,3,24,24)
x_np = x[0, :, :, :].permute([1, 2, 0]).numpy() * 255
x_np = albu_shadow(image=x_np)['image']
```
error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tsunyi/anaconda3/envs/pytorch/lib/python3.7/site-packages/albumentations/core/transforms
_interface.py", line 87, in __call__    return self.apply_with_params(params, **kwargs)
  File "/home/tsunyi/anaconda3/envs/pytorch/lib/python3.7/site-packages/albumentations/core/transforms
_interface.py", line 100, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))
  File "/home/tsunyi/anaconda3/envs/pytorch/lib/python3.7/site-packages/albumentations/augmentations/transforms.py", line 2053, in apply
    return F.add_shadow(image, vertices_list)
  File "/home/tsunyi/anaconda3/envs/pytorch/lib/python3.7/site-packages/albumentations/augmentations/functional.py", line 54, in wrapped_function
    result = func(img, *args, **kwargs)
  File "/home/tsunyi/anaconda3/envs/pytorch/lib/python3.7/site-packages/albumentations/augmentations/functional.py", line 997, in add_shadow
    cv2.fillPoly(mask, vertices, 255)
TypeError: Expected Ptr<cv::UMat> for argument 'img'
```

**Comment by Dipet** [comment]
Very interesting.
Problem how pytorch, numpy and OpenCV share memory.
Until we find solution how to resolve problem you can use this fix to avoid problem:
```
x_np = albu_shadow(image=x_np.astype(np.uint8).coy())['image']
```
You need directly create numpy copy of image before provide it into albumentations transfromation

**Comment by shamangary** [comment]
Thank you for your prompt response!

**Comment by michal-kierzynka** [comment]
It's been some time since this issue has been closed but it seems to me the problem is still there. For the abovementioned snippet: 

```import torch
import numpy as np
import albumentations as albu

albu_shadow = albu.RandomShadow(p=1, num_shadows_lower=1, num_shadows_upper=1, shadow_dimension=5, shadow_roi=(0, 0.5, 1, 1))

x = torch.rand(1,3,24,24)
x_np = x[0, :, :, :].permute([1, 2, 0]).numpy() * 255
x_np = albu_shadow(image=x_np.astype(np.uint8))['image']
```
I receive the following output:
```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    x_np = albu_shadow(image=x_np.astype(np.uint8))['image']
  File "/home/michal/miniconda3/envs/test/lib/python3.8/site-packages/albumentations/core/transforms_interface.py", line 90, in __call__
    return self.apply_with_params(params, **kwargs)
  File "/home/michal/miniconda3/envs/test/lib/python3.8/site-packages/albumentations/core/transforms_interface.py", line 103, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))
  File "/home/michal/miniconda3/envs/test/lib/python3.8/site-packages/albumentations/augmentations/transforms.py", line 1381, in apply
    return F.add_shadow(image, vertices_list)
  File "/home/michal/miniconda3/envs/test/lib/python3.8/site-packages/albumentations/augmentations/functional.py", line 54, in wrapped_function
    result = func(img, *args, **kwargs)
  File "/home/michal/miniconda3/envs/test/lib/python3.8/site-packages/albumentations/augmentations/functional.py", line 915, in add_shadow
    cv2.fillPoly(mask, vertices, 255)
cv2.error: OpenCV(4.5.3) :-1: error: (-5:Bad argument) in function 'fillPoly'
> Overload resolution failed:
>  - Layout of the output array img is incompatible with cv::Mat (step[ndims-1] != elemsize or step[1] != elemsize*nchannels)
>  - Expected Ptr<cv::UMat> for argument 'img'

```

I have the following versions of libraries:
albumentations            1.0.3
numpy                     1.21.2
pytorch                   1.9.1

Anybody can help?

**Comment by Dipet** [comment]
The image is not contiguous after permute, change the augs call to this:
```python
x_np = albu_shadow(image=np.ascontiguousarray(x_np.astype(np.uint8)))['image']
```

**Comment by michal-kierzynka** [comment]
Thanks, it works. Another example to illustrate the problem:

```import numpy as np
import albumentations as albu

albu_ch_shuffle = albu.ChannelShuffle(p=1)
albu_shadow = albu.RandomShadow(p=1)

img = np.random.rand(100,100,3) * 255
img = img.astype(np.uint8)

img = albu_ch_shuffle(image=img)['image']
img = albu_shadow(image=np.ascontiguousarray(img))['image']
```
With `np.ascontiguousarray` works, without doesn't, as expected after studying this thread.

Now, I have a list of possible augmentations as `albumentations.Compose` and `ChannelShuffle` and `RandomShadow` are among them. I want to be able to apply both for the same image. How can I nicely apply `np.ascontiguousarray` after every call to `ChannelShuffle`?

**Comment by Dipet** [comment]
Why are you using augs separately?
Just combine them into single `Compose`
```python
import numpy as np
import albumentations as albu

augs = albu.Compose([
    albu.ChannelShuffle(p=1),
    albu.RandomShadow(p=1)
])

img = np.random.rand(100,100,3) * 255
img = img.astype(np.uint8)

res = augs(image=np.ascontiguousarray(img))["image"]
```

**Comment by michal-kierzynka** [comment]
@Dipet This doesn't change anything. The above code results in:
```
cv2.error: OpenCV(4.5.3) :-1: error: (-5:Bad argument) in function 'fillPoly'
> Overload resolution failed:
>  - Layout of the output array img is incompatible with cv::Mat (step[ndims-1] != elemsize or step[1] != elemsize*nchannels)
>  - Expected Ptr<cv::UMat> for argument 'img'
```

The problem is that `np.ascontiguousarray` needs to be applied after `ChannelShuffle`, and you cannot control this if you have `Compose`. One workaround is:

```
aug = albumentations.Compose([
    albumentations.OneOf([
        albumentations.ChannelShuffle(p=0.5),
        albumentations.RandomShadow(p=0.5)
])
```

But it doesn't solve the problem when you want to apply both operations to the same image.

**Comment by Dipet** [comment]
I can not reproduce the problem
```python
import albumentations
import numpy as np
import random

seed = 0
random.seed(seed)
np.random.seed(seed)

aug = albumentations.Compose(
    [albumentations.ChannelShuffle(p=1), albumentations.RandomShadow(p=1)]
)

for _ in range(1000):
    aug(image=np.zeros([100, 100, 3], dtype=np.uint8))
```

**Comment by michal-kierzynka** [comment]
What are your library versions? Mine are listed above.

**Comment by Dipet** [comment]
Good point! Thank you for your comment. I reproduced that problem in the last version.
I think we could resolve this problem by just adding `np.ascontiguousarray` for the image there https://github.com/albumentations-team/albumentations/blob/master/albumentations/core/transforms_interface.py#L97
