### ISSUE TITLE
TypeError: Expected Ptr<cv::UMat> for argument 'src'

### ISSUE THREAD

**Issue by Adblu** [albumentations-team/albumentations#706]
I am trying various transforms to the image, however few of them gives an error as in the title. 
Here is full traceback:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/snap/pycharm-community/209/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/snap/pycharm-community/209/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/n/Documents/mmdetection/augumentation/ExtraAugumemtation_custom.py", line 107, in <module>
    results = albu_transform(results)
  File "/home/n/Documents/mmdetection/mmdetection/mmdet/datasets/pipelines/transforms.py", line 1153, in __call__
    results = self.aug(**results)
  File "/home/n/.conda/envs/mm/lib/python3.7/site-packages/albumentations/core/composition.py", line 176, in __call__
    data = t(force_apply=force_apply, **data)
  File "/home/n/.conda/envs/mm/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 87, in __call__
    return self.apply_with_params(params, **kwargs)
  File "/home/n/.conda/envs/mm/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 100, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))
  File "/home/n/.conda/envs/mm/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 226, in apply_to_masks
    return [self.apply_to_mask(mask, **params) for mask in masks]
  File "/home/n/.conda/envs/mm/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 226, in <listcomp>
    return [self.apply_to_mask(mask, **params) for mask in masks]
  File "/home/n/.conda/envs/mm/lib/python3.7/site-packages/albumentations/augmentations/transforms.py", line 529, in apply_to_mask
    return F.rotate(img, angle, cv2.INTER_NEAREST, self.border_mode, self.mask_value)
  File "/home/n/.conda/envs/mm/lib/python3.7/site-packages/albumentations/augmentations/functional.py", line 70, in wrapped_function
    result = func(img, *args, **kwargs)
  File "/home/n/.conda/envs/mm/lib/python3.7/site-packages/albumentations/augmentations/functional.py", line 202, in rotate
    return warp_fn(img)
  File "/home/n/.conda/envs/mm/lib/python3.7/site-packages/albumentations/augmentations/functional.py", line 188, in __process_fn
    img = process_fn(img, **kwargs)
TypeError: Expected Ptr<cv::UMat> for argument 'src'
```

Here is the part of the config.

```
config = dict(
    type='Albu',
    transforms=[
        dict(type='HorizontalFlip', p=0.7),
        dict(type='Rotate', p=1, limit=(-10,10)),
    ]
)
```

## Environment

 - Albumentations version '0.4.6'
 - Python version  3.7
 - OS Ubuntu
 - How you installed albumentations - PIP

What might be the cause ?

**Comment by BloodAxe** [comment]
The most probable cause of this is wrong image type. Albumentations works only with numpy arrays.
Based on the context of your stacktrace, it's maybe not the case. I'm not familiar with mmdetection, but I assume it may be sending PIL image directly to our pipeline.
