### ISSUE TITLE
Getting a Type Error: clahe supports only uint8 inputs

### ISSUE THREAD

**Issue by Anubhav1107** [albumentations-team/albumentations#731]
## 🐛 Bug
```
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "<ipython-input-151-9ec7bc2b47b2>", line 46, in __getitem__
    sample =self.transforms(**sample)
  File "/opt/conda/lib/python3.7/site-packages/albumentations/core/composition.py", line 176, in __call__
    data = t(force_apply=force_apply, **data)
  File "/opt/conda/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 87, in __call__
    return self.apply_with_params(params, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 100, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))
  File "/opt/conda/lib/python3.7/site-packages/albumentations/augmentations/transforms.py", line 2644, in apply
    return F.clahe(img, clip_limit, self.tile_grid_size)
  File "/opt/conda/lib/python3.7/site-packages/albumentations/augmentations/functional.py", line 70, in wrapped_function
    result = func(img, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/albumentations/augmentations/functional.py", line 669, in clahe
    raise TypeError("clahe supports only uint8 inputs")
TypeError: clahe supports only uint8 inputs
```

I am getting a type error when I tried to use the Clahe in albumentation on dataset.

## To Reproduce

1.
       ```
        image = cv2.imread(self.img_dir+image_id+'.jpg',cv2.IMREAD_COLOR)
        image = cv2.cvtColor(image,cv2.COLOR_BGR2RGB).astype(np.float32)
        image = image/255.0
        
            return image,target,image_id]

```
The image is in normal and .jpg format. If I don't use clahe, it works with no problem
This is my Albumentation code

```
```
def train_trans():
    return al.Compose([
    al.Flip(0.5),
    al.HorizontalFlip(p=0.5),
    al.VerticalFlip(p=0.5),
    al.OneOf([al.RandomContrast(),
             al.RandomGamma(),
             al.RandomBrightness()],p=1.0),
    
    al.CLAHE(p=0.1),ToTensorV2(p=1.0)], bbox_params ={'format':'pascal_voc','label_fields':['labels']})
```

```
## Expected behavior

I expected to get my images transformed using clahe

## Environment

I am using the Environment in a kaggle notebook.
Everything is preinstalled here
## Additional context

I am a beginner in this and I think there must be a problem for data type. I am not sure and it will be great if someone can help

**Comment by Dipet** [comment]
If you will look to [documentations about this transform](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.CLAHE) you can see that it is supports only `uint8` data type.
Do image normalization in the last step because not all transforms can work with `float` data type. Another reason to use `uint8` data type - it is much more faster then float

**Comment by Anubhav1107** [comment]
but when  I try to read the image as np.uint8. It gives
a big error with 
KeyError: dtype('float64')
