### ISSUE TITLE
ValueError: Requested crop size (64, 64) is larger than the image size (48, 128)

### ISSUE THREAD

**Issue by SagarJiyani3010** [albumentations-team/albumentations#822]
ValueError: Caught ValueError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/tez/datasets/image_classification.py", line 43, in _getitem_
    augmented = self.augmentations(image=image)
  File "/opt/conda/lib/python3.7/site-packages/albumentations/core/composition.py", line 182, in _call_
    data = t(force_apply=force_apply, **data)
  File "/opt/conda/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 89, in _call_
    return self.apply_with_params(params, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 102, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))
  File "/opt/conda/lib/python3.7/site-packages/albumentations/augmentations/transforms.py", line 742, in apply
    return F.center_crop(img, self.height, self.width)
  File "/opt/conda/lib/python3.7/site-packages/albumentations/augmentations/functional.py", line 312, in center_crop
    crop_height=crop_height, crop_width=crop_width, height=height, width=width
ValueError: Requested crop size (64, 64) is larger than the image size (48, 128)

**Comment by Dipet** [comment]
Your image size less than crop size. Try to use `PadIfNeeded` before crop
