### ISSUE TITLE
ValueError: Requested crop size (720, 720) is larger than the image size (4221, 3)

### ISSUE THREAD

**Issue by sujiMahendran** [albumentations-team/albumentations#882]
I am passing both image and its mask image in albumentation as below:
  ```
  if list(masks) and bboxes is not None:
            transformed = transform(image=image, bboxes=bboxes, class_labels=class_labels, masks=list(masks))
```
both image and its mask before passing in function has the same shape as image = (7283, 4221,3), masks = (7283, 4221,3)
while using the `albumentations.RandomCrop(height=720, width=720, p=1)` method, I got this error
```
Traceback (most recent call last):
  File "train_net_aug.py", line 331, in <module>
    args=(args,),
  File "/home/dsm/install/detectron2_/nsw2/detectron2/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "train_net_aug.py", line 317, in main
    return trainer.train()
  File "/home/dsm/install/detectron2_/nsw2/detectron2/detectron2/engine/defaults.py", line 431, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/dsm/install/detectron2_/nsw2/detectron2/detectron2/engine/train_loop.py", line 138, in train
    self.run_step()
  File "/home/dsm/install/detectron2_/nsw2/detectron2/detectron2/engine/defaults.py", line 441, in run_step
    self._trainer.run_step()
  File "/home/dsm/install/detectron2_/nsw2/detectron2/detectron2/engine/train_loop.py", line 226, in run_step
    data = next(self._data_loader_iter)
  File "/home/dsm/install/detectron2_/nsw2/detectron2/detectron2/data/common.py", line 179, in __iter__
    for d in self.dataset:
  File "/home/dsm/anaconda3/envs/nsw2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/dsm/anaconda3/envs/nsw2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/dsm/anaconda3/envs/nsw2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/dsm/anaconda3/envs/nsw2/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/dsm/anaconda3/envs/nsw2/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/dsm/anaconda3/envs/nsw2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dsm/anaconda3/envs/nsw2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dsm/install/detectron2_/nsw2/detectron2/detectron2/data/common.py", line 43, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/dsm/install/detectron2_/nsw2/detectron2/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/home/dsm/PMT/code/detectron2_projects/nsw_table_det_v2/mapper/AlbuMapperv2_fix.py", line 244, in __call__
    transformed = transform(image=image, bboxes=bboxes, class_labels=class_labels, masks=list(masks))
  File "/home/dsm/anaconda3/envs/nsw2/lib/python3.7/site-packages/albumentations/core/composition.py", line 182, in __call__
    data = t(force_apply=force_apply, **data)
  File "/home/dsm/anaconda3/envs/nsw2/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 89, in __call__
    return self.apply_with_params(params, **kwargs)
  File "/home/dsm/anaconda3/envs/nsw2/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 102, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))
  File "/home/dsm/anaconda3/envs/nsw2/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 230, in apply_to_masks
    return [self.apply_to_mask(mask, **params) for mask in masks]
  File "/home/dsm/anaconda3/envs/nsw2/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 230, in <listcomp>
    return [self.apply_to_mask(mask, **params) for mask in masks]
  File "/home/dsm/anaconda3/envs/nsw2/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 227, in apply_to_mask
    return self.apply(img, **{k: cv2.INTER_NEAREST if k == "interpolation" else v for k, v in params.items()})
  File "/home/dsm/anaconda3/envs/nsw2/lib/python3.7/site-packages/albumentations/augmentations/transforms.py", line 775, in apply
    return F.random_crop(img, self.height, self.width, h_start, w_start)
  File "/home/dsm/anaconda3/envs/nsw2/lib/python3.7/site-packages/albumentations/augmentations/functional.py", line 337, in random_crop
    crop_height=crop_height, crop_width=crop_width, height=height, width=width
ValueError: Requested crop size (720, 720) is larger than the image size (4221, 3)
```
and came to notice that the shape in the function random_crop has taken as  `img.shape[:2] (4221, 3)`

**Comment by BloodAxe** [comment]
Please attach a fully reproducible minimal example. It's very likely you have some permutation that mess channel order somewhere before random crop.

**Comment by sujiMahendran** [comment]
> Please attach a fully reproducible minimal example. It's very likely you have some permutation that mess channel order somewhere before random crop.

@BloodAxe I just create a mask image using annotations instead of opening the image through opencv, here is the code I used below:
        image = utils.read_image(dataset_dict["file_name"], format=self.image_format)  #array
        h, w, b = image.shape
        name=dataset_dict["file_name"]
        
        name = name.split('/')[-1]
        utils.check_image_size(dataset_dict, image)
        output = np.zeros_like(image)
        bboxes = [ann["bbox"] for ann in dataset_dict['annotations']]
        segmentations = [ann["segmentation"] for ann in dataset_dict['annotations']]
        masks = convert_coco_poly_to_mask(segmentations, h, w)
        masks = masks.numpy()
        np_msk = np.array(masks,dtype='bool')
        mask_array = np.moveaxis(np_msk, 0, -1)
        num_instances = masks.shape[0]   #mask count
        print('num_instances',num_instances,name)
        mask_array_instance = []
        for i in range(num_instances):
            mask_array_instance.append(mask_array[:, :, i:(i+1)])
            masks = np.where(mask_array_instance[i] == True,255,output)
        labels = [ann['category_id'] for ann in dataset_dict['annotations']]
        class_labels = [CLASSES[label] for label in labels]
        if list(masks) and bboxes is not None:

             transformed = transform(image=image, bboxes=bboxes, class_labels=class_labels, masks=list(masks))

There is no transformation before albumentation

**Comment by sujiMahendran** [comment]
sorry, my fault, a single spelling mistake in using attributes in `transform`. Now only noticed that there is a difference in `mask` (for one image) and `masks` (for multiple images)
