### ISSUE TITLE
[TensorFlow] Is albumentations compatible with TF image_dataset_from_directory?

### ISSUE THREAD

**Issue by roma-glushko** [albumentations-team/albumentations#905]
## 🐛 Bug

I have tried to use albumentations with TF (flowing images through image_dataset_from_directory generator), but I have got quite a few issues when applied some augmentations on my dataset.

My images are taken from the classic rock-paper-scissors dataset which I grabbed from Kaggle https://www.kaggle.com/frtgnn/rock-paper-scissor. The images are 300x300 RGB PNGs with 3-channels.

My dataset pipeline looks this way ([reference](https://github.com/roma-glushko/rock-paper-scissor/blob/0.1.0-bugrep/rock_paper_scissors/datasets.py#L16)):

```python
def augment_image(inputs, labels, augmentation_pipeline: a.Compose):
    def apply_augmentation(images):
        aug_data = augmentation_pipeline(image=images.astype('uint8'))
        return aug_data['image']

    inputs = tf.numpy_function(func=apply_augmentation, inp=[inputs], Tout=tf.uint8)

    return inputs, labels


def get_dataset(
        dataset_path: str,
        subset_type: str,
        augmentation_pipeline: a.Compose,
        validation_fraction: float = 0.2,
        batch_size: int = 32,
        image_size: Tuple[int, int] = (300, 300),
        seed: int = 42
) -> tf.data.Dataset:
    augmentation_func = partial(
        augment_image,
        augmentation_pipeline=augmentation_pipeline,
    )

    dataset = image_dataset_from_directory(
        dataset_path,
        subset=subset_type,
        class_names=class_names,
        validation_split=validation_fraction,
        image_size=image_size,
        batch_size=batch_size,
        seed=seed,
    )

    return dataset \
        .map(augmentation_func, num_parallel_calls=AUTOTUNE) \
        .prefetch(AUTOTUNE)

```

Now, I tried to add the following augmentations and got the errors below:

- a.MotionBlur(p=1.0, blur_limit=(3, 7)):
```
Traceback (most recent call last):
  File "train.py", line 110, in <module>
    train()
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/morty/config/main_decorator.py", line 35, in decorated_main
    run_func_with_config(
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/morty/config/main_decorator.py", line 92, in run_func_with_config
    run_func(config)
  File "train.py", line 91, in train
    training_history = model.fit(
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/wandb/integration/keras/keras.py", line 124, in new_v2
    return old_v2(*args, **kwargs)
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1183, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3023, in __call__
    return graph_function._call_flat(
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1960, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 591, in call
    outputs = execute.execute(
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown:  error: OpenCV(4.5.2) /tmp/pip-req-build-dzetuct2/opencv/modules/core/src/matrix.cpp:1102: error: (-215:Assertion failed) dims <= 2 && step[0] > 0 in function 'locateROI'
```

- a.HueSaturationValue(always_apply=False, p=1.0, hue_shift_limit=(-20, 20), sat_shift_limit=(-30, 30), val_shift_limit=(-20, 20))
```
Traceback (most recent call last):
  File "train.py", line 110, in <module>
    train()
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/morty/config/main_decorator.py", line 35, in decorated_main
    run_func_with_config(
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/morty/config/main_decorator.py", line 92, in run_func_with_config
    run_func(config)
  File "train.py", line 91, in train
    training_history = model.fit(
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/wandb/integration/keras/keras.py", line 124, in new_v2
    return old_v2(*args, **kwargs)
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1183, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3023, in __call__
    return graph_function._call_flat(
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1960, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 591, in call
    outputs = execute.execute(
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown:  error: OpenCV(4.5.2) /tmp/pip-req-build-dzetuct2/opencv/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<3>; VDepth = cv::impl::{anonymous}::Set<0, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

Traceback (most recent call last):

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 645, in wrapper
    return func(*args, **kwargs)

  File "/tmp/tmpehq9938k.py", line 16, in apply_augmentation
    aug_data = ag__.converted_call(ag__.ld(augmentation_pipeline), (), dict(image=ag__.converted_call(ag__.ld(images).astype, ('uint8',), None, fscope_1)), fscope_1)

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 463, in _call_unconverted
    return f(*args, **kwargs)

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/albumentations/core/composition.py", line 182, in __call__
    data = t(force_apply=force_apply, **data)

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/albumentations/core/transforms_interface.py", line 89, in __call__
    return self.apply_with_params(params, **kwargs)

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/albumentations/core/transforms_interface.py", line 102, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/albumentations/augmentations/transforms.py", line 2234, in apply
    return F.shift_hsv(image, hue_shift, sat_shift, val_shift)

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/albumentations/augmentations/functional.py", line 54, in wrapped_function
    result = func(img, *args, **kwargs)

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/albumentations/augmentations/functional.py", line 417, in shift_hsv
    img = _shift_hsv_uint8(img, hue_shift, sat_shift, val_shift)

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/albumentations/augmentations/functional.py", line 357, in _shift_hsv_uint8
    img = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)

cv2.error: OpenCV(4.5.2) /tmp/pip-req-build-dzetuct2/opencv/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<3>; VDepth = cv::impl::{anonymous}::Set<0, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

```
- a.ImageCompression(always_apply=False, p=1.0, quality_lower=80, quality_upper=100, compression_type=0)
```
Traceback (most recent call last):
  File "train.py", line 110, in <module>
    train()
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/morty/config/main_decorator.py", line 35, in decorated_main
    run_func_with_config(
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/morty/config/main_decorator.py", line 92, in run_func_with_config
    run_func(config)
  File "train.py", line 91, in train
    training_history = model.fit(
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/wandb/integration/keras/keras.py", line 124, in new_v2
    return old_v2(*args, **kwargs)
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1183, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3023, in __call__
    return graph_function._call_flat(
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1960, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 591, in call
    outputs = execute.execute(
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown:  error: OpenCV(4.5.2) /tmp/pip-req-build-dzetuct2/opencv/modules/imgcodecs/src/grfmt_base.cpp:150: error: (-10:Unknown error code -10) Raw image encoder error: Maximum supported image dimension is 65500 pixels in function 'throwOnEror'

Traceback (most recent call last):

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 645, in wrapper
    return func(*args, **kwargs)

  File "/tmp/tmpevsad93u.py", line 16, in apply_augmentation
    aug_data = ag__.converted_call(ag__.ld(augmentation_pipeline), (), dict(image=ag__.converted_call(ag__.ld(images).astype, ('uint8',), None, fscope_1)), fscope_1)

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 340, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 463, in _call_unconverted
    return f(*args, **kwargs)

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/albumentations/core/composition.py", line 182, in __call__
    data = t(force_apply=force_apply, **data)

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/albumentations/core/transforms_interface.py", line 89, in __call__
    return self.apply_with_params(params, **kwargs)

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/albumentations/core/transforms_interface.py", line 102, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/albumentations/augmentations/transforms.py", line 1708, in apply
    return F.image_compression(image, quality, image_type)

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/albumentations/augmentations/functional.py", line 54, in wrapped_function
    result = func(img, *args, **kwargs)

  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/albumentations/augmentations/functional.py", line 799, in image_compression
    _, encoded_img = cv2.imencode(image_type, img, (int(quality_flag), quality))

cv2.error: OpenCV(4.5.2) /tmp/pip-req-build-dzetuct2/opencv/modules/imgcodecs/src/grfmt_base.cpp:150: error: (-10:Unknown error code -10) Raw image encoder error: Maximum supported image dimension is 65500 pixels in function 'throwOnEror'



         [[{{node PyFunc}}]]
         [[IteratorGetNext]]
  (1) Unknown:  error: OpenCV(4.5.2) /tmp/pip-req-build-dzetuct2/opencv/modules/imgcodecs/src/grfmt_base.cpp:150: error: (-10:Unknown error code -10) Raw image encoder error: Maximum supported image dimension is 65500 pixels in function 'throwOnEror'
```
- a.ISONoise(always_apply=False, p=1.0, intensity=(0.1, 0.5), color_shift=(0.01, 0.05))

```
Traceback (most recent call last):
  File "train.py", line 110, in <module>
    train()
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/morty/config/main_decorator.py", line 35, in decorated_main
    run_func_with_config(
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/morty/config/main_decorator.py", line 92, in run_func_with_config
    run_func(config)
  File "train.py", line 91, in train
    training_history = model.fit(
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/wandb/integration/keras/keras.py", line 124, in new_v2
    return old_v2(*args, **kwargs)
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1183, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3023, in __call__
    return graph_function._call_flat(
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1960, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 591, in call
    outputs = execute.execute(
  File "/home/deepstation/Projects/rock-paper-scissor/.venv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown:  error: OpenCV(4.5.2) /tmp/pip-req-build-dzetuct2/opencv/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<3>; VDepth = cv::impl::{anonymous}::Set<0, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

```

Looking at the provided example (https://albumentations.ai/docs/examples/tensorflow-example/), is this correct assumption that albumentations doesn't work with `image_dataset_from_directory` generator?

## To Reproduce

1. Clone the project state at `0.1.0-bugrep` tag: 
```
git clone --depth 1 --branch 0.1.0-bugrep https://github.com/roma-glushko/rock-paper-scissor
```
2. Pull dataset:
```
cd data
kaggle datasets download --unzip frtgnn/rock-paper-scissor
```
3. Install project deps:
```
poetry install
```
4. Uncomment any of the reported augmentations in the config file (they are all commented out in the git):
https://github.com/roma-glushko/rock-paper-scissor/blob/master/configs/basic_config.py

5. Run training:

```
python train.py
```

## Expected behavior

I anticipate that the dataset images and my data loading pipeline are regular and not specific to be able to freely apply mentioned augmentations without workarounds. 

## Environment

 - Albumentations version (e.g., 0.1.8): 0.5.2
 - Python version (e.g., 3.7): 3.8.6
 - OS (e.g., Linux): Ubuntu 20.10
 - How you installed albumentations (`conda`, `pip`, source): poetry (pip-like)
 - tensorflow-gpu: 2.5.0 (for the sake of compatibility with RTX3070 (ampere arch.))

**Comment by roma-glushko** [comment]
As it was discussed in #911, the albumentations expects to get a single image as input, otherwise you may experience issues I described there and here.

So whenever you use `image_dataset_from_directory()` to load your images, make sure to do the following in augmentation step:

```python
def augment_image(inputs, labels, augmentation_pipeline: a.Compose, seed: int = 42):
    def apply_augmentation(images):
        random.seed(seed)
        np.random.seed(seed)

        augmented_images = []

        for img in images:  # apply augmentation pipeline to single image (not to the batch)
            aug_data = augmentation_pipeline(image=img.astype('uint8'))
            augmented_images.append(aug_data['image'])

        return np.stack(augmented_images)

    inputs = tf.numpy_function(func=apply_augmentation, inp=[inputs], Tout=tf.uint8)

    return inputs, labels
```

This should help.

**Comment by fjzs** [comment]
OMG @roma-glushko I was looking for this for 5 days now
ty very much!
